mongodb/mongodb-kubernetes-operator

mongodb-kubernetes-operator/deploy/crds/mongodb.com_mongodbs_crd.yaml
mongodb-kubernetes-operator/deploy/crds/mongodb.com_v1_mongodb_cr.yaml
mongodb-kubernetes-operator/kube/statefulset/statefulset.go
mongodb-kubernetes-operator/pkg/apis/mongodb/v1/mongodb_types.go
mongodb-kubernetes-operator/pkg/controller/mongodb/mongodb_controller.go

This PR removes a lot of the boiler plate code (generate busy box pod) and replaces it with creating a StatefulSet that uses a community mongodb image.
The following resource 
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
name: example-mongodb
spec:
members: 3
kind: ReplicaSet
version: "4.0.6"
```
Produces the following pods and stateful set
```bash
NAME              READY   AGE
example-mongodb   5/5     10m  # StatefulSet
NAME                                           READY   STATUS    RESTARTS   AGE
example-mongodb-0                              1/1     Running   0          4m48s
example-mongodb-1                              1/1     Running   0          3m30s
example-mongodb-2                              1/1     Running   0          3m
example-mongodb-3 …
```

CLOUDP-57661: Create basic stateful set from CR

---

cmd/manager/main.go
deploy/crds/mongodb.com_mongodbs_crd.yaml
pkg/controller/mongodb/mongodb_controller.go

This PR fixes errors while reconciling the MongoDB resource
1. The logger needed to be configured globally to display error messages in the reconciliation loop
2. podSpec.labels need to match label selectors

Fix logger and stateful set construction

---

cmd/manager/main.go
deploy/crds/mongodb.com_v1_mongodb_cr.yaml
deploy/operator.yaml
pkg/controller/mongodb/mongodb_controller.go
pkg/controller/mongodb/replicaset_controller_test.go
pkg/kube/resourcerequirements/resource_requirements.go
pkg/kube/resourcerequirements/resource_requirements_test.go

This PR configures the stateful set to use an agent image specified by the `AGENT_IMAGE` environment variable.
The stateful set is configured with default resource requirements. Sample StatefulSet configuration
```bash
spec:
podManagementPolicy: OrderedReady
replicas: 3
revisionHistoryLimit: 10
selector:
matchLabels:
dummy: label
serviceName: ""
template:
metadata:
creationTimestamp: null
labels:
dummy: label
spec:
containers:
- command:
- agent/mongodb-agent
- -cluster=/var/lib/automation/config/automation-config.json
image: <agent-image>
imagePullPolicy: Always
name: mongodb-agent
resources:
limits:
cpu: "1"
memory: 500M
requests:
cpu: 500m
memory: 400M
```

CLOUDP-58090: Create StatefulSet that starts agent image

---

docker/Dockerfile.operator
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_test.go
pkg/controller/mongodb/mongodb_controller.go
pkg/controller/mongodb/replicaset_controller_test.go

This PR adds a local copy of the version manifest to the operator image. When constructing the automation config, only the relevant builds are added.
An e2e test will be added which tests version change after the test improvements made in #28

CLOUDP-58413: Deploy any version of MongoDB

---

go.mod
pkg/kube/statefulset/statefulset.go
pkg/kube/statefulset/statefulset_test.go

This PR adds a function which will compare only the changed fields on StatefulSet that we are building. This allows us to construct a stateful set struct that does not include all of the fields that are populated by the api server when doing a comparison.

CLOUDP-60686: Create HaveEqualSpec function and tests

---

.evergreen.yml
scripts/ci/run_test.sh

This PR adds the building and pushing of the test runner image on each evergreen run
Evg: https://evergreen.mongodb.com/version/5ea84373d1fe07711489f9e7

Build Test Runner image for every evergreen run

---

README.md

[JIRA](https://jira.mongodb.org/browse/DOCSP-9305)
Adds installation and basic deploy instructions to the readme.

(DOCSP-9305): Simple CRD/install instructions

---

deploy/crds/mongodb.com_mongodb_crd.yaml
pkg/apis/mongodb/v1/mongodb_types.go

This PR updates the types to generate the correct crd using
`operator-sdk generate crds`

Updated plural and short name of MongoDB crd

---

.evergreen.yml
test/e2e/feature_compatibility_version/feature_compatibility_version_test.go
test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go
test/e2e/mongodbtests/mongodbtests.go

Added 2 new e2e tests that check FCV configurations:
* feature_compatibility_version: Changes the DB version from 4.0 to 4.2 while keeping the FCV to 4.0. It downgrades the DB *back* to 4.0.
* feature_compatibility_version_upgrade: Changes the DB version from 4.0 to 4.2 and *then* updates the FCV to 4.2

Added FeatureCompatibilityVersion e2e test

---

README.md
architecture.md

[JIRA](https://jira.mongodb.org/browse/DOCSP-10035)
This PR:
- Creates an [architecture topic](https://github.com/melissamahoney-mongodb/mongodb-kubernetes-operator/blob/DOCSP-10035/architecture.md)
- Updates the [readme](https://github.com/melissamahoney-mongodb/mongodb-kubernetes-operator/blob/DOCSP-10035/README.md#contribute) to point to the architecture topic
I've spoken to @LouisPlisso about getting diagrams. I can take a screenshot from the [Google doc](https://docs.google.com/document/d/1XR7E6daNGI8QITmZjfHzI9-EBoiBy18aZfgtnqYF9lA/edit#) if I have to, or we can wait to add them.

(DOCSP-10035): Add architecture docs

---

README.md
deploy/operator.yaml

CLOUDP-65077: Release 0.0.6

---

cmd/testrunner/crds/crds.go
deploy/crds/mongodb.com_mongodb_crd.yaml
pkg/apis/mongodb/v1/mongodb_types.go

This PR adds CRD generation annotation to enforce the replica set type as an enum
~~CRD was generated with `operator-sdk generate crds`~~
`operator-sdk generate crds --crd-version v1beta1`
There is an [issue with v1 CRD generation](https://github.com/operator-framework/operator-sdk/issues/3005)

Ensure enum values for type

---

architecture.md
pkg/controller/mongodb/mongodb_controller.go

This PR adds a description of the pre-stop hook init container and the volumes to `architecture.md`. There was a TODO comment for this.

CLOUDP-65697: Add init container and volumes to architecture doc

---

pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go

This PR adds the settings necessary to implement TLS/SSL to the automation config. It only adds the old `ssl` fields and not the new `tls` fields in 4.2. This will be fixed in a later PR.

CLOUDP-65806: Add TLS/SSL settings to automation config

---

cmd/prestop/main.go

Before this PR, our pre-stop hook couldn't correctly identify a version change and would restart the pod for all automation config changes. This was because the hook would check for a `WaitFeatureCompatibilityVersionCorrect` move in the automation plan. Unfortunately, this move is used for most automation config changes and not just version changes.
After talking with the agent team, we came to the conclusion that it should be possible to only look for the `ChangeVersion` move. The reason this hadn't worked until now was that the agent wouldn't immediately write the plan to file and the hook would hence read an outdated version of the health status.
With this PR, we change the hook to wait until the health status file has been updated and the latest plan is available. We do this by …

CLOUDP-65917: Fix pre-stop hook status check

---

pkg/apis/mongodb/v1/mongodb_types.go
pkg/controller/mongodb/mongodb_controller.go
pkg/controller/mongodb/replicaset_controller_test.go
pkg/kube/client/mocked_client.go
test/e2e/e2eutil.go
test/e2e/feature_compatibility_version/feature_compatibility_version_test.go
test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_change_version/replica_set_test.go

Our strategy for changing the StatefulSet update strategy to OnDelete was not working as intended.
Our isReady check was not working, as once we set the strategy to OnDelete, this no longer triggers a rolling upgrade. We need a mechanism to track if the StatefulSet became un-ready while being set to OnDelete. I used annotations for this purpose.

Fixed OnDelete strategy

---

deploy/operator.yaml

#73 fixes a few issues in the pre-stop hook. These fixes are now available in quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.1 and this PR updates our example deployments to use the new image.

Upgrade pre-stop hook to 1.0.1 in example deployment files

---

scripts/dev/dump_diagnostic.py

Sometimes our E2E tests fail when trying to dump the logs at the end. This is caused by the logs sometimes containing non-ASCII characters like 𝜇. This PR fixes this issue by writing the logs in UTF-8 encoding.

Set encoding to UTF-8 when reading logs after E2E tests

---

pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
pkg/controller/mongodb/mongodb_controller.go
pkg/controller/mongodb/replicaset_controller_test.go

This PR updates the automation config to use the new "tls" settings instead of the now deprecated "ssl" ones. The agent was updated to 10.15 with #86 and the new version can automatically fall back to "ssl" for older version of MongoDB. This PR also updates all internal SSL references to TLS instead.

CLOUDP-66801: Switch to "tls" settings

---

deploy/crds/mongodb.com_mongodb_crd.yaml
pkg/apis/mongodb/v1/mongodb_types.go
pkg/controller/mongodb/mongodb_tls.go
pkg/controller/mongodb/replicaset_controller_test.go
test/e2e/e2eutil.go
test/e2e/setup/setup.go

This PR adds TLS settings to the CRD. The design we settled upon looks like this:
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
name: example-mongodb
spec:
members: 3
type: ReplicaSet
version: "4.2.8"
security:
tls:
enabled: true
caConfigMapRef:
name: "example-mongodb-ca"
certificateKeySecretRef:
name: "example-mongodb-tls"
```

CLOUDP-67051: Update CRD with TLS settings

---

.gitignore
scripts/dev/dump_diagnostic.py
scripts/dev/k8s_request_data.py

CLOUDP-66908: add configmap to evg logs

---

pkg/authentication/scramcredentials/scram_credentials.go
pkg/authentication/scramcredentials/scram_credentials_test.go

This PR moves the Credential generating logic from the enterprise code base to community. There are no functional changes. I've added additional unit tests for Sha256 secret generation.

Add functions to generate Scram Credentials

---

pkg/authentication/scram/scram.go
pkg/authentication/scram/scram_enabler.go
pkg/authentication/scram/scram_enabler_test.go
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
pkg/controller/mongodb/mongodb_authentication.go
pkg/controller/mongodb/mongodb_controller.go
pkg/controller/mongodb/mongodb_tls.go
pkg/controller/mongodb/replicaset_controller_test.go

This PR refactors authentication (SCRAM-SHA) and TLS to use a unified way of setting up the automation config. We introduce a new `Modification` function for the automation config, similar to the functional builders used for Kubernetes objects. The builder is changed to accept these generic modification functions instead of having special fields for TLS and authentication. This way we reduce the operators knowledge about authentication and TLS and make the automation config simpler to extend.
With this PR we also re-arrange `automation_config.go` as the current order of types and functions is inconsistent and not top-down. There have been no other changes to that file.

Refactor authentication and TLS with unified automation config modification

---

pkg/controller/watch/watch.go
pkg/controller/watch/watch_test.go
pkg/util/contains/contains.go

This PR implements a custom `handler.EventHandler` called `ResourceWatcher`. This will allow us to watch for changes to specific secondary resources outside of the main MDB CRD. This PR is part of the work to implement support for TLS certificate rotations. The idea is to have one `ResourceWatcher` on the `Reconciler` for each resource type we want to watch. If we for example have a `secretWatcher` on our `Reconciler` we can register it like:
```
// Watch for changes to primary resource MongoDB
err = c.Watch(&source.Kind{Type: &mdbv1.MongoDB{}}, &handler.EnqueueRequestForObject{}, predicates.OnlyOnSpecChange())
if err != nil {
return err
}
// Watch for changes to secondary Secrets
err = c.Watch(&source.Kind{Type: &corev1.Secret{}}, r.secretWatcher)
if err != nil {
return err
}
``` …

Add ability to watch secondary resources

---

pkg/kube/client/client.go
pkg/kube/client/client_test.go
pkg/kube/client/mocked_client.go
pkg/kube/configmap/configmap.go

This PR adds a simple function to delete ConfigMaps which is consistent with our current patterns.

Add Delete Function for ConfigMap

---

go.mod
go.sum
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_test.go
pkg/controller/mongodb/mongodb_tls.go
pkg/controller/mongodb/mongodb_tls_test.go

This PR is in preparation for CLOUDP-58544 which adds support for arbitrary MongoDB configuration in the CRD. To support this change, we need to treat "args2_6" as a generic map, instead of a hard-coded struct.
To simplify interactions with the map, this PR uses the objx library: https://github.com/stretchr/objx. The library helps us write better code with less typecasting without having to write our helper functions. On top of that, it also includes support for merging maps which will be helpful for the next PR. Based on the following criteria I feel that the library is good enough to be included in our code base:
- Maturity: the library has been around for a while and is very well-tested. Most issues have been closed and no major features seem to be missing.
- Pulse: the library isn't …

Use generic map for "args2_6" in automation config

---

.evergreen.yml
go.mod
pkg/apis/mongodb/v1/mongodb_types.go
pkg/controller/mongodb/replica_set_controller.go
pkg/controller/mongodb/replicaset_controller_test.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_mongod_config/replica_set_mongod_config_test.go

This PR adds support for overriding mongod configuration in the CRD. Any settings will override the default ones without exception and the same settings must be used for all members.

CLOUDP-58544: Add support for arbitrary mongod config in CRD

---

.evergreen.yml
scripts/dev/dockerfile_generator.py
scripts/dev/templates/Dockerfile.template

Update Operator SDK to version v0.18.2 and tag golang at 1.14

---

cmd/testrunner/crds/crds.go
cmd/testrunner/main.go
cmd/versionhook/main.go
pkg/authentication/scram/scram.go
pkg/authentication/scramcredentials/scram_credentials.go
pkg/controller/mongodb/mongodb_tls.go
pkg/controller/mongodb/replica_set_controller.go
pkg/controller/mongodb/replicaset_controller_test.go
pkg/kube/configmap/configmap.go
pkg/kube/pod/pod.go
pkg/kube/pod/pod_test.go
pkg/kube/secret/secret.go
pkg/kube/statefulset/statefulset_builder.go
scripts/ci/download.go
test/e2e/e2eutil.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_tls/replica_set_tls_test.go
test/e2e/replica_set_tls_rotate/replica_set_tls_rotate_test.go
test/e2e/replica_set_tls_upgrade/replica_set_tls_upgrade_test.go
test/e2e/setup/setup.go
test/e2e/tlstests/tlstests.go

This PR updates the codebase to use `pkg/errors.Errorf` in place of `fmt.Errorf`
the format strings have been updated to use `%s` (the intended mechanism for handling errors in format strings)

Ensure consistent errors

---

cmd/versionhook/main.go
pkg/agent/agentflags.go
pkg/agent/agentflags_test.go
pkg/agent/agenthealth.go
pkg/kube/container/containers.go

This PR adds a `WithAgentFlags` function that sets up the `AGENT_FLAGS` environment variable from a slice of env var representing single agent startup flags.

add WithAgentFlags function

---

test/e2e/mongodbtests/mongodbtests.go

We still have some failures from time to time in our `e2e_readiness_probe`: https://evergreen.mongodb.com/task/mongodb_kubernetes_operator_e2e_tests_e2e_test_replica_set_readiness_probe_3b8ea122eb9953a12326d0285c03b2869bbbdd94_20_08_26_12_28_25/0
`[2020/08/26 12:40:09.830] panic: Log in goroutine after TestReplicaSetReadinessProbeScaling/MongoDB_is_reachable has completed`
calling `t.Log` inside a goroutine is considered wrong and we added a `nolint` in the past for the exact reason. Since the log isn't fundamental for our testing, I would just remove it. 
Note that all the test have actually passed when we reach the line that causes that error
There's also a change in another line due to the linter complaining

Removed log call in goroutine

---

scripts/dev/dump_diagnostic.py
scripts/dev/k8s_request_data.py

We are now storing the Automation Config in a secret, so we need to read the configs from secrets instead.
EVG: https://evergreen.mongodb.com/version/5f182ca7562343139d5d49b0

Read Automation Config from Secret instead of ConfigMap

---

.evergreen.yml

This PR should fix the error encountered during the latest release:
https://evergreen.mongodb.com/task/mongodb_kubernetes_operator_release_images_quay_release_operator_patch_2957f6a75cb4e98fcf0aa7ec94b62ddb74898e15_5f4699083627e02af45eb038_20_08_26_17_16_57

Fix release task

---

test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set/replica_set_test.go

This PR introduces a new function which gets any given admin parameter and updates the replica set test to check for cluster auth mode.
TODO: in future PRs
*  Update TLS tests to check for this also 
* Add this check as one that gets run on every test

CLOUDP-66666: Update Replica Set test to check for the clusterAuthMode admin setting

---

pkg/controller/mongodb/replica_set_controller.go

This PR introduces a mechanism to customise headless service according to cluster dns name.
New Additions - 
- `CLUSTER_DNS_NAME` env var in operator deployment
closes #180

Added CLUSTER_DNS_NAME env variable to customise headless service 

---

requirements.txt
scripts/dev/dockerutil.py

This PR updates our tooling to display a progress bar in the form of.
```bash
Pushing image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/chatton/test-runner:latest
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:15<00:00,  6.50it/s]
Building image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/chatton/e2e:latest
Successfully built image!
Pushing image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/chatton/e2e:latest
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:01<00:00, …
```

Added progress bar to dev tooling

---

pkg/controller/mongodb/mongodb_tls_test.go
pkg/kube/statefulset/statefulset.go
pkg/kube/statefulset/statefulset_test.go

This PR changes the default permissions on volumes created from a secret. This is needed for another work in the enterprise operator. It will still be possible to specify different modes through the yaml file (when the merging bug is fixed)

Change default permissions for volumes created from secret

---

pkg/kube/podtemplatespec/podspec_template.go
pkg/kube/podtemplatespec/podspec_template_test.go

This PR fixes the volume merging by manually merging by name volumes and volumesources
As discussed with @chatton, for now we focus on merging the values of VolumeSource for which the operator fills default values (Secret, ConfigMap, EmptyDir) and we overwrite the volume if a different one is provided.
A few new unit tests are introduced as well.
More comments to come inline

CLOUDP-73217: fix volumes merging

---

docs/architecture.md
docs/contributing.md
docs/deploy-configure.md
docs/install-upgrade.md
docs/users.md
scripts/git-hooks/pre-commit

Since moving some documentation inside the `docs` directory, some links became 404, so I fixed the path for them.
I also removed the link to the `operator-sdk` e2e-test docs, as they were moved to a `legacy` section of the website but now have been completely removed from it.
Unrelated but needed to submit the PR: a fix to the pre-commit hook (`mapfile` on an empty array returns an array with one empty element thus breaking the go linter)
Auto-formatter also removed a bunch of whitespace, which I don't think should be an issue but happy to revert if needed somewhere

Fix broken docs link

---

docs/deploy-configure.md
docs/install-upgrade.md
docs/users.md

Minor fixes to documentation
Also resolves: https://github.com/mongodb/mongodb-kubernetes-operator/issues/223
* [ n/a] Have you opened an Issue before filing this PR?
* [ n/a] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ n/a] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ n/a] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

Minor fixes to documentation

---

.gitignore
deploy/crds/mongodb.com_mongodb_crd.yaml
deploy/crds/mongodb.com_v1_mongodb_cr.yaml
deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml
deploy/crds/mongodb.com_v1_mongodb_scram_cr.yaml
deploy/crds/mongodb.com_v1_mongodb_tls_cr.yaml
docs/users.md
go.mod
pkg/apis/mongodb/v1/mongodb_types.go
pkg/apis/mongodb/v1/mongodb_types_test.go
pkg/authentication/scram/scram.go
pkg/authentication/scram/scram_test.go
test/e2e/e2eutil.go

This PR changes the logic for SCRAM credential secret name generation for MongoDB users (to accommodate for non DNS1123 complying user name). For a more detailed discussion please refer to the corresponding JIRA ticket.
Note: This change breaks backward compatibility
* [n/a ] Have you opened an Issue before filing this PR?
* [n/a] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [n/a] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [n/a] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

CLOUDP-74820: change in scram credential secret name generation

---

deploy/crds/mongodb.com_mongodb_crd.yaml
pkg/apis/mongodb/v1/mongodb_types.go
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
pkg/controller/mongodb/replica_set_controller.go

When running MongoDB on Kubernetes, members of the replica set discover each other using the cluster-internal DNS name. When exposing this replica set through a NodePort, clients such as Mongoose are unable to connect, because the replica set document references the cluster-internal DNS name.
MongoDB has a currently undocumented feature where the replica set can respond to "isMaster" requests with different hostnames and ports, if contacted via alternate names using TLS. See https://jira.mongodb.org/browse/SERVER-40156 for more details. This implementation makes use of that.
Note, no validation is currently performed; it is currently possible to mis-configure by having different `members` from the number of array elements in the `horizons` field.
Example configuration:
```yaml
apiVersion: …
```

Add support for split horizon in replica set.

---

test/e2e/replica_set_readiness_probe/replica_set_readiness_probe_test.go

This fixes a linting issue found (and ignored) in #279. golangci-lint compains about the use of the `math/rand` package in this test, so this change switches to using the `crypto/rand` package.
Link to ticket: https://jira.mongodb.org/browse/CLOUDP-80411

CLOUDP-80411: Change math/rand to crypto/rand in test

---

deploy/crds/mongodb.com_mongodb_crd.yaml
deploy/crds/mongodb.com_v1_mongodb_custom_role.yaml
pkg/apis/mongodb/v1/mongodb_types.go
pkg/apis/mongodb/v1/zz_generated.deepcopy.go
pkg/controller/mongodb/replica_set_controller.go
test/e2e/replica_set_custom_role/replica_set_custom_role_test.go

Refactor custom roles in crd

---

pkg/controller/mongodb/mongodb_status_options.go
pkg/util/apierrors/apierrors.go
pkg/util/apierrors/apierrors_test.go

This PR lowers the severity of the transient `the object has been modified; please apply your changes to the latest version and try again` error

Added IsTransient function to check if an error is transient or not

---

deploy/clusterwide/role.yaml
deploy/operator/role.yaml

Fixes use of old/incorrect resource plural in role.yaml and removes need for '*' permission.

Fix use of incorrect crd plural in role.yaml

---

pkg/util/merge/merge_podtemplate_spec.go

We weren't sorting hostaliases when merging, so the order was not predictable as ranging over a map has no guarantees on the order. This caused a flaky unit test.
I've ran this test locally around 10 times with no failures.

Fixed merging of host aliases

---

docs/install-upgrade.md

closes #316 
[JIRA](https://jira.mongodb.org/browse/DOCSP-13959)

(DOCSP-13959): cross-namespace deployment docs

---

Makefile
agent/Dockerfile
cmd/manager/main.go
config/manager/manager.yaml
controllers/mongodb_tls_test.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
deploy/openshift/operator_openshift.yaml
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
release.json
scripts/dev/templates/Dockerfile.operator

This PR upgrades the agent version to a version which supports allowing versions of MongoDB which are not present in the version manifest.
* The version manifest has been removed from the operator image.
* A dummy version config is being used in the automation config.
* The agent version has been upgraded.
closes #255

Removed dependency on version manifest

---

.evergreen.yml
test/e2e/replica_set_tls/replica_set_tls_test.go

This fixes the flakey TLS test. Just copies the existing statement from the green test (`replica_set_tls_rotate_test.go`)

CLOUDP-83416: fix flakey TLS test

---

api/v1/mongodbcommunity_types.go
controllers/mongodb_authentication.go
controllers/replicaset_controller_test.go
pkg/authentication/scram/mock_types_test.go
pkg/authentication/scram/scram.go
pkg/authentication/scram/scram_test.go
pkg/kube/secret/secret.go

We were including the agent password + keyfile in a single secret, but these are not required to be kept together, this PR separates them into separate secrets and renames the volume to a more meaningful name.

Separate Keyfile & Password into separate secrets

---

controllers/build_statefulset_test.go
controllers/mongodb_authentication.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
controllers/testdata/change_data_volume.yaml
controllers/testdata/custom_storage_class.yaml
controllers/testdata/openshift_mdb.yaml
controllers/testdata/tolerations_example.yaml
controllers/testdata/volume_claim_templates_mdb.yaml
pkg/automationconfig/automation_config.go
pkg/kube/resourcerequirements/resource_requirements.go

We previously had not had a log volume set, so logs were being lost with pod restarts. The logging settings were also being misconfigured.
they were set at process[.].systemLog rather than the correct process[n].args2_6.systemLog, the previous settings were being ignored by the agent as the field was not being recognized.

CLOUDP-83838: Fix logging configuration and add volume for logs

---

controllers/mongodb_tls.go
controllers/mongodb_tls_test.go
controllers/replica_set_controller.go
pkg/kube/client/mocked_manager.go
test/e2e/e2eutil.go
test/e2e/feature_compatibility_version/feature_compatibility_version_test.go
test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_change_version/replica_set_test.go
test/e2e/replica_set_multiple/replica_set_multiple_test.go
test/e2e/replica_set_readiness_probe/replica_set_readiness_probe_test.go
test/e2e/replica_set_scale/replica_set_scaling_test.go
test/e2e/replica_set_tls_upgrade/replica_set_tls_upgrade_test.go

This PR fixes the flakey tls upgrade test. The issue was that we were continuing the test without waiting for the agents to reach goal state.

CLOUDP-83615: Fix flakey upgrade tls test

---

.evergreen.yml
agent/Dockerfile
cmd/manager/main.go
scripts/ci/build_and_push_agent_image.sh
scripts/ci/config.json
scripts/dev/dev_config.py
scripts/dev/e2e.py
test/e2e/setup/setup.go
test/e2e/setup/test_config.go

This PR updates the agent Dockerfile to remove the old readiness probe which is no longer being used. (it has been replaced by the readiness probe copied from the init container)
In order to test this, I have also updated our ci to build the agent image for each evergreen run. And each of our tests will use the image built. There is a little duplication of our build & push scripts which will be addressed in a future PR.

CLOUDP-83929: Build agent image in evergreen & remove old readiness probe

---

api/v1/mongodbcommunity_types.go
controllers/construct/mongodbstatefulset.go

This PR adds a `Persistence()` method to the interface for building the statefulset.
In community, persistence is always true, but this will be used in the appdb options on enterprise

added persistence option

---

api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml
scripts/git-hooks/pre-commit
test/e2e/e2eutil.go

closes #312
This PR makes the additional mongod field nullable in order to prevent the presence of the field in all resource specifications.

CLOUDP-83820: Make additionalMongod config nullable

---

cmd/manager/main.go
config/samples/mongodb.com_v1_mongodbcommunity_openshift_cr.yaml
controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go
controllers/replicaset_controller_test.go
controllers/testdata/openshift_mdb.yaml
docs/deploy-configure.md
pkg/util/envvar/envvars.go
test/e2e/setup/setup.go
test/e2e/setup/test_config.go

We weren't correctly using the `MANAGED_SECURITY_CONTEXT` env var, which is needed only in the operator and not in MongoDB pods. 
This PR uses this env var when building the Statefulset, and it adds security context to the pods only when it is not set.
It also refactors usage of env vars, to avoid duplication

Added MANAGED_SECURITY_CONTEXT check and refactored env vars

---

controllers/construct/mongodbstatefulset.go

This PR separates the part of the agent command that is common between monitoring and automation to the one that only goes to automation. This way we can reuse the constants in enterprise to configure monitoring.
* [n/a] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [n/a] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

Extract agent command common to monitoring and automation

---

config/rbac/role.yaml
deploy/e2e/role.yaml

Added - mongodbcommunity/finalizers to the mongodbcommunity.mongodb.com ApiGroup in role.yaml. 
Fixes the StatefulSet creation on OpenShift 4.5. closes #367

CLOUD-84084 Added - mongodbcommunity/finalizers to role. Fixes the StatefulSet creation on OpenShift 4.5

---

api/v1/mongodbcommunity_types.go
api/v1/mongodbcommunity_types_test.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
dev_notes/RELEASE_NOTES.md
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
test/e2e/e2eutil.go
test/e2e/replica_set_change_version/replica_set_test.go

This PR changes how to handle FCV when upgrading, to fix the issue when an upgrade such as 4.2.x -> 4.4.x would change the FCV to 4.4 and agents would never reach goal state

Changed FCV handling when upgrading

---

pkg/readiness/health/health.go
pkg/readiness/health/health_test.go

Checks for `replicationStatusUndefined` for standalones and sharded clusters.
I also added tests for all of the possible states, to make it clear as to what is checked by the readiness probe.
Please note that `readiness-probe:1.0.2` was built with these changes, but I forgot to add them to the previous PR.

Adds replicationStatusUndefined.

---

.github/workflows/close-stale-issues.yml

*Reviewers*: please review for correctness - but also for the set of config options I've selected here; let me know if you think they'll lead to a bad experience

CLOUDP-85550: mark github issues stale

---

pipeline.py

The release flag was being triggered with every task. A value of true was returned if the field was specified at all, it does not account for the value of the bool.

Fix incorrect arg parse field

---

api/v1/mongodbcommunity_types.go
controllers/construct/mongodbstatefulset.go

This method was added to support the AppDB project. 
However, there is no need (and it's actually harmful) to allow customers to specify persistence=false in the AppDB, and we never supported that here in Community.
This PR completely removes the method from the interface and an analogous PR on Enterprise will remove it from the AppDB

CLOUDP-85272: remove persistence method from interface

---

.github/workflows/close-stale-issues.yml

The stale action was exiting prematurely with the message:
`Warning: Reached max number of operations to process. Exiting.`
(see https://github.com/mongodb/mongodb-kubernetes-operator/runs/2434307103?check_suite_focus=true)
This is reported here: https://github.com/actions/stale/issues/95
and fixed here: https://github.com/actions/stale/pull/97
This way we will start with older issues first and then move to newer ones. We will still exit prematurely but missing only new issues.
We could increase `operations-per-run`(https://github.com/marketplace/actions/close-stale-issues#operations-per-run) but I wanted to try with a safer approach

Fix warning message in Stale action 

---

inventory.yaml
pipeline.py
scripts/ci/config.json
scripts/dev/dev_config.py

This PR makes the S3 bucket configurable. This allows the s3 dockerfile publishing to be run against dev s3 buckets. The evergreen config file points at the one we release to as part of the release task.

Make docker file S3 bucket configurable

---

controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go

This PR ensures that the logs of the Mongod are displayed upon restart, previously they were being written to a log file and not displayed when the container was restarted.

CLOUDP-89359: Ensure Mongod logs are sent to stdout upon restart

---

dev_notes/dev-quick-start.md
scripts/ci/config.json
scripts/dev/dev_config.py
scripts/dev/e2e.py
test/e2e/setup/setup.go
test/e2e/setup/test_config.go

This PR ensures that the readiness probe and version upgrade hooks that we build every run are used in our e2e tests.

Allow readiness probe to be configurable in test runs

---

cmd/readiness/testdata/k8sobjects.go
pkg/readiness/pod/podannotation.go
pkg/readiness/pod/podannotation_test.go

Closes #482 
After this is merged a new version of the `readiness-probe` image must be released.

Fix pod annotations overwrite

---

controllers/replica_set_controller.go
dev_notes/RELEASE_NOTES.md

When we refactored the project to use the latest versions of the Operator SDK, we accidentally removed the set of predicates that we pass. This change ensures that the operator reconciles only on spec changes (not on status updates / other changes ) made by itself or other entities.

Add predicates to controller

---

pkg/automationconfig/automation_config_builder.go

This is needed in AppDB works when performing a TLS upgrade from an Agent that understands only SSL to one that understands TLS

Allows both TLS and SSL to be specified

---

.evergreen.yml

Fix e2e_test_feature_compatibility_version_upgrade to run feature_compatibility_version_upgrade instead of feature_compatibility_version

Fix .evergreen.yaml

---

inventories/e2e-inventory.yaml
inventories/operator-inventory.yaml
inventory.yaml
pipeline.py
scripts/ci/config.json
scripts/dev/dev_config.py
scripts/dev/e2e.py

This PR ensures that the values from ~/.community-operator/config.json are substituted into the inventory.yaml files and so are the single source of truth throughout the development pipeline.

Ensure Inventory files use images specified in config.json

---

.evergreen.yml
cmd/readiness/main.go
controllers/construct/mongodbstatefulset.go
deploy/e2e/role.yaml
go.sum
test/e2e/client.go
test/e2e/e2eutil.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_mongod_readiness/replica_set_mongod_readiness_test.go
test/e2e/replica_set_recovery/replica_set_recovery_test.go

This is an e2e test for readiness improvements. 
The test executes into the container, moves the important data file and kills the mongod process (otherwise mongod will work fine until any data is written).
Then the test makes sure the `mongodb-agent` container becomes not ready.
Finally the test fixes the situation by moving the file back
**Update** I tried to set the `failureThreshold` to a much lower value (4) but this broke upgrade procedures, so I had to keep it high (though decreased from 60 to 40)

CLOUDP-89260: e2e test for readiness probe

---

pkg/kube/client/client.go
pkg/kube/service/service.go

This PR adds a `deleteService` method to the client package. This is needed for CLOUDP-79509 (enterprise)

CLOUDP-79509: Added deleter interface

---

.evergreen.yml
requirements.txt

* Updates tooling to Python3.9
* Updates build and release hosts to ubuntu1804-small (much higher capacity, 600 vs 200 of ubuntu1604-small)
* Fixes a certificate validation error when accessing Atlas mongodb over TLS ([like this one](https://spruce.mongodb.com/task/mongodb_kubernetes_operator_release_images_quay_release_agent_ubuntu_patch_f923235f9a4673f6aeb3e826e549d58814e4f39b_60c0fc520305b93bd2261e55_21_06_09_17_37_22/logs?execution=0))

Updates image release process.

---

pkg/kube/service/service.go

Following discussion on https://github.com/10gen/ops-manager-kubernetes/pull/1599 we move the method to community.

Moved DeleteServiceIfItExists to Community

---

test/e2e/e2eutil.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/util/wait/wait.go

This PR moves waiting related code out of the generic `util` package into the new `wait` package.

Move Wait functions into separate package

---

scripts/dev/dump_diagnostic.py

We were previously only dumping the StatefulSet spec, not the MongoDBCommunity spec in our e2e tests.

Include MongoDBCommunity resource spec in diagnostics

---

.github/workflows/release-single-image.yml

This is largely a duplicate of the release all images github action that was added recently. 
This action allows us to manually run any image providing the pipeline argument and the key in release.json

Added Single Image Github Action

---

docs/install-upgrade.md

Added quotes to * because it created an error without it.

Fixing the small issue with *

---

scripts/dev/run_e2e_gh.sh

Task ID is not immediately visible as soon as you create the task, we must wait a few seconds for it to start, then we can open it.

Fix script to launch github action

---

controllers/replica_set_controller.go
docs/RELEASE_NOTES.md

This increased the number of parallels reconciles for the operator -- this should increase the speed of reconciling.

Test increasing number of parallel reconciles

---

.github/workflows/e2e.yml

It is not possible to depend on a `strategy matrix` job (without individually specifying each generated task)
This Pr introduces a job that will fail if any e2e tests have failed. We can block PRs on this job.

Added job e2e-success

---

Makefile
scripts/dev/get_e2e_env_vars.py

This PR ensures the correct env vars are set based on the development config file when using `make run`

Configure Env Vars with make run

---

.github/workflows/create-release-pr.yml
.github/workflows/release-images.yml

This PR adds a github action which will link the related release on the PR once the release is drafted.

Added action to link the relevant github release to the release PR

---

config/manager/kustomization.yaml
docs/RELEASE_NOTES.md
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_secret_test.go

closes #570 
by not defaulting to saving `mongodb` logs to file. Users can still obtain the old behaviour through `spec.additionalMongodConfig`

CLOUDP-92631: mongodb log to stdout

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/RELEASE_NOTES.md
docs/install-upgrade.md

Changed repo url and image name

---

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
docs/RELEASE_NOTES.md
docs/contributing.md
scripts/dev/get_e2e_env_vars.py

This PR adds the missing env vars so that `make run` works correctly.
Updated release notes to remove notes from the 0.6.2 release that went out.

Added required env vars for make run to work correctly

---

.github/workflows/remove-label.yml

As discussed, we can remove the label any time a PR is updated to make the fork approval process smoother.
It succeeds in the case of no label.

Remove safe-to-test label any time a PR is updated

---

.action_templates/e2e-fork-template.yaml
.action_templates/e2e-pr-template.yaml
.action_templates/events/pull-request-target.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
requirements.txt

Dependabot PRs are supplied with a **read only** GitHub token. This means that secrets are not passed to our tests, which means our tests cannot run.
This PR updates the condition for which our tests run which should allow the use of the `safe-to-test` label on dependabot PRs.

Fix Dependabot PRs

---

.action_templates/steps/setup-kind-cluster.yaml
.github/workflows/e2e-dispatch.yml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml

Kind GithubAction was causing failures during setup of cluster.
Setting up the cluster manually seems to fix this issue.

Use "run" script instead of GH Action to install kind

---

test/e2e/setup/setup.go

Tested it by changing the parameters of the field "operatorImage" in the testConfig on line 28 in test/e2e/setup/setup.go to "blah".

CLOUDP-91632: E2E tests should fail fast if the operator pod doesn't reach READY state

---

controllers/replica_set_controller.go

While debugging with spec in MongoDB to configure service name, we found `logw` doesn't print the Spec completely.

Replace logw with logf - logw doesn't print the Spec fields

---

Makefile
PROJECT
api/v1/doc.go
api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
config/crd/kustomizeconfig.yaml
config/manager/kustomization.yaml
docs/RELEASE_NOTES.md

Kubernetes is removing support for `v1beta1` CRD from version 1.22. This PR migrates the Community CRD to version `v1`.

CLOUDP-65796: Update CRD from v1beta1 to v1

---

api/v1/mongodbcommunity_types.go
config/samples/arbitrary_statefulset_configuration/mongodb.com_v1_custom_volume_cr.yaml
config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
docs/RELEASE_NOTES.md
test/e2e/mongodbtests/mongodbtests.go
test/e2e/statefulset_arbitrary_config/statefulset_arbitrary_config_test.go

Tested by adding 
statefulSet:
spec:
serviceName: database
to the custom resource yaml file and running make run to observe that the serviceName field now contains database and by setting the service name in statefulset_arbitrary_config_test.go and checking the name is correctly set in mongodbtests.go

CLOUDP-93590: Service name configurable

---

scripts/dev/e2e.py
test/e2e/client.go
test/e2e/setup/setup.go

Tested by running replica_set test and observing that after the following resources do not exist:
e2e-test: pod, clusterrole, clusterrolebinding, serviceaccount
mongodb-kubernetes-operator: deployment, role, role binding, service account
I did not delete the namespace.
Note that it will only delete those resources if they do not exist before (the delete functions are registered upon creation, not when existing resources are only updated). Thus, please make sure to delete any e2e-related resources before running a new e2e test.

CLOUDP-90175: cleanup all resources

---

.github/workflows/comment-release-pr.yml
.github/workflows/release-images.yml
docs/how-to-release.md

There were a few issues with the release process. This PR makes some changes.
* Remove the merge action. This was not working correctly as if there are other E2E tests running, this can cause the merge to fail and interrupt the release process. We can leave this as a manual action.
* Only comment on releases **after** the PR is merged. Previously it was commenting too early.

Fix Github Actions for Release

---

Makefile
pkg/kube/configmap/configmap_builder.go
scripts/dev/e2e.py
test/e2e/e2eutil.go
test/e2e/setup/setup.go

This PR adds the label `e2e-test: true` to resources created by the tests. This allows for easy cleanup. A new make target has been added which runs before running and tests. This causes cleanup of resources before any new tests run.

Add test labels to test resources and cleanup before running a new test

---

controllers/mongodb_tls_test.go
pkg/kube/client/mocked_client_test.go
pkg/kube/configmap/configmap_builder.go
pkg/kube/configmap/configmap_test.go
test/e2e/setup/setup.go

Fixes the discussion [here](https://github.com/10gen/ops-manager-kubernetes/pull/1737#discussion_r675650367).

Add SetData method to configmap builder

---

deploy/clusterwide/role.yaml
deploy/clusterwide/role_binding.yaml
docs/install-upgrade.md

Fixes missing entries for `secrets` permissions in cluster role - closes #661 
Fixes missing verb `create` for statefulset in cluster role - closes #664 
Adds a placeholder and documentation on the serviceaccount namespace in the clusterrolebinding subject closes #663 
For the last one I created an internal ticket - CLOUDP-97033 to provide a better solution for the users.

Fix clusterwide issues

---

api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml

This PR makes the CRD backward compatible to operator 0.7.0. by making status.version optional.
To test:
Run the operator manually by applying the manager.yaml which uses operator 0.7.0, there should be no status.version error in the logs of the operator pod.

CLOUDP-97302: Make status.version in CRD backward compatible.

---

controllers/replica_set_controller.go
helm-chart/templates/tests/operator.yaml
test/e2e/mongodbtests/mongodbtests.go
test/e2e/statefulset_delete/statefulset_delete_test.go

This PR ensures that the reconciliation loop is started when the user deletes the sts or a pod created by the sts.

CLOUDP-96891: operator does not recreate sts on being deleted

---

Makefile

We were missing a few values when using helm in a dev environment. This PR adds a set of values requires to run `make deploy` and then deploy a CR.

Add all helm values to makefile

---

pkg/kube/container/container_test.go
pkg/kube/container/containers.go

This change will be imported in enterprise-operator

Make DefaultSecurityContext return a pointer to security context to align with corev1.SecurityContext

---

pkg/helm/helm.go
pkg/kube/configmap/configmap.go
pkg/kube/configmap/configmap_test.go
pkg/kube/secret/secret.go
pkg/kube/secret/secret_test.go
test/e2e/replica_set_cross_namespace_deploy/replica_set_cross_namespace_deploy_test.go
test/e2e/util/wait/wait.go

This PR adds a convenience function to check whether a secret exists or not.
Note: all changes not to `secret.go` are either to fix pre-commit errors or introduced by `gofmt`

Added secret exists method 

---

.github/config_files/config_lint.yaml
.github/config_files/config_lint_clusterwide.yaml
.github/config_files/config_lint_openshift.yaml

Our kube-linter check is failing because our openshit yaml violates this new rule that was introduced with the most recent release of kube-linter.
There isn't currently a way to ping a kubelinter version in the GH action but I created an issue on their repo here: https://github.com/stackrox/kube-linter-action/issues/8 
In the meantime we can disable the check

Remove non-isolated-pod check

---

docs/deploy-configure.md

This allows users to be aware of the current limitation which prevents
clusters from starting when specifying loosely-defined tags in MongoDB
image version.

Add spec.version limitations to deploy docs (#758)

---

pkg/kube/podtemplatespec/podspec_template.go
pkg/kube/podtemplatespec/podspec_template_test.go

This would enable us to patch volumes more cleanly, currently, it would be used to configure volumes when vault is configured or not.

Add "WithVolumes" API to podspec template

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/RELEASE_NOTES.md
docs/how-to-release.md
release.json
scripts/ci/update_release.py

Prepares release for a new version for a new Helm Chart (https://github.com/mongodb/helm-charts/pull/80).
I have scripted some of the missing steps for the new out-of-band Helm Chart.

Release MongoDB Kubernetes Operator v0.7.2

---

pkg/authentication/scram/mock_types_test.go
pkg/automationconfig/automation_config_secret_test.go
pkg/kube/client/client.go
pkg/kube/secret/secret.go
pkg/kube/secret/secret_test.go

This is needed for vault secret backend, if in future we need to pass more params,
we can consider wrapping it in a struct

Pass optional string in secret methods

---

api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
controllers/mongodb_status_options.go
controllers/replica_set_controller.go
docs/RELEASE_NOTES.md
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go
pkg/util/scale/scale.go
pkg/util/versions/versions.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_arbiter/replica_set_arbiter_test.go
test/e2e/util/wait/wait.go

- Deploys arbiters to a new (different) StatefulSet to be able to scale both arbiters and members independently.
- RFC is here (private): https://github.com/10gen/ops-manager-kubernetes/pull/2064

CLOUDP-105706: Arbiters go into own Statefulset

---

api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
controllers/validation/validation.go

Arising from #764: adding some validation to make sure that `scramCredentialsSecretName` is unique among users

CLOUDP-104426: multiple users issue

---

api/v1/mongodbcommunity_types.go
api/v1/mongodbcommunity_types_test.go
controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
controllers/testdata/specify_net_port.yaml
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_builder.go
pkg/util/merge/merge_automationconfigs_test.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_mongod_config/replica_set_mongod_config_test.go

This addresses #839 and moves `mongod` configurations handled by the operator to the `MongodConfiguration` type.

Make mongod port configurable

---

config/manager/manager.yaml

Setting the `RuntimeDefault` seccomp profile is required for running the operator under the Restricted policy of [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).
Note that this PR only enables running the operator itself under the Restricted policy, and not the MongoDB StatefulSets created by the operator. For the latter, further changes are required: https://github.com/mongodb/mongodb-kubernetes-operator/issues/833

Compatibility with Restricted PodSecurityPolicy (Operator Only)

---

scripts/dev/templates/agent/Dockerfile.ubi

Updates the agent image to use ubi8-minimal instead of ubi7.

CLOUDP-105593: Agent image to ubi8-minimal

---

.action_templates/e2e-fork-template.yaml
.action_templates/e2e-pr-template.yaml
.action_templates/jobs/e2e-success.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml

This PR removes a github action that is no longer required (this was failing on forks but is not an actual test.)

Remove Unused Github Action

---

pkg/util/merge/merge.go
pkg/util/merge/merge_test.go

Fixes:  https://github.com/mongodb/mongodb-kubernetes-operator/issues/818
This patch prevents the operator to merge command/args in containers.  It uses the one specified in the CR as the source of truth(if specified). The problem with the merging is highlighted in the linked issue. If a user removes a command/arg from a container the operator since it is currently merging the new commands/args with the old ones, it is keeping the removed args lurking around as well.

CLOUDP-107815: Do not append stale command/args to containers

---

docs/install-upgrade.md

Fixes https://github.com/mongodb/mongodb-kubernetes-operator/issues/875

Fix broken link to clusterwide clusterRoleBinding

---

pkg/authentication/scram/scram.go
pkg/authentication/scram/scram_test.go

- Fixes #879 
Username with underscore in name will prevent Secret from being created.
Open questions:
- Should we add other characters to be replaced as well?

Fix Secret creation with username with rfc-1123 non-allowed-chars.

---

pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go

This PR tries to fix #889 by not to not try to access non-declared split horizon DNS records.
The issue occurs during scaling down, as the automation config is tried to be built with actual numbers of replicas with desired split-horizon dns records. Then a panic with out of range on the related slice is triggered.
Closes #889
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>

fix(pkg/automationconfig): do not try to access non-declared split horizon dns records

---

.action_templates/jobs/tests.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
config/samples/mongodb.com_v1_mongodbcommunity_prometheus.yaml
controllers/replica_set_controller.go
go.mod
go.sum
pkg/automationconfig/automation_config.go
pkg/monitoring/monitoring.go
release.json
test/e2e/client.go
test/e2e/e2eutil.go
test/e2e/prometheus/prometheus_test.go
test/e2e/util/mongotester/mongotester.go

Using latest agent, we can pass a `spec.metrics.prometheus` configuration that will result in an automation_config change that *enables a `/metrics` endpoint that can be used with Prometheus.*
We need to publish a new agent version before these changes are even recognized by the agents.

Accepts `metrics.prometheus` endpoint.

---

Makefile
README.md
api/v1/mongodbcommunity_types.go
config/samples/mongodb.com_v1_mongodbcommunity_prometheus.yaml
controllers/prometheus.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
docs/prometheus/README.md
docs/prometheus/issuer-and-cert.yaml
docs/prometheus/mongodb-prometheus-sample.yaml
pkg/kube/service/service_builder.go

- Configured the MongoDB `Service` adding the prometheus Port.
- Created a simple YAML file and Readme to be able to test the prometheus integration so far.

Updates service and documents servicemonitor

---

api/v1/mongodbcommunity_types.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
controllers/replica_set_controller.go
docs/RELEASE_NOTES.md
docs/deploy-configure.md
test/e2e/replica_set_arbiter/replica_set_arbiter_test.go
test/e2e/util/wait/wait.go

Fixes arbiters by using the same service to handle both regular (data-bearing) statefulset and arbiters statefulset. Now arbiters can be scaled from 0 (PSS->PSA) or starting from scratch. The e2e test has been fixed (wait.go), and I've added clarification on the docs about how arbiters work.

Fixes arbiters not reaching running phase.

---

Makefile

In go1.17 installing binaries using go get is deprecated and removed in 1.18.
https://go.dev/doc/go-get-install-deprecation

Use go install in Makefile instead of go get

---

test/e2e/setup/setup.go

One of the e2e tests (replica_set_operator_upgrade, ubi) is flaky. 
This is to try running e2e tests with increased timeout.

Increased timeout when waiting to deploy operator in e2e tests

---

docs/build_operator_locally.md
docs/contributing.md
requirements.txt
scripts/dev/setup_kind_cluster.sh

Improved `scripts/dev/setup_kind_cluster.sh`:
* added switch: -n <cluster_name> to specify kind cluster's
name. 
* added switch: -e to export kind credentials after creating cluster
Example usage: 
`scripts/dev/setup_kind_cluster.sh -en test-cluster` - creates test-cluster in Kind and sets current kubectl context to it.
Improved docs.

Create local kind cluster with specified name

---

.github/workflows/e2e-dispatch.yml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
Makefile
controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go
pkg/kube/container/containers.go
pkg/kube/podtemplatespec/podspec_template.go

This Pull Request removes `securityContext` set on container level and moves all the previously used settings to the pod level. Note, that previously the pod level settings didn't make any effect as they were overriden by the container level.

CLOUDP-125628 security context update

---

Makefile
controllers/replica_set_controller.go
pkg/util/scale/scale.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_arbiter/replica_set_arbiter_test.go

This Pull Request changes the order of creating the automation config and the StatefulSet upon first bootup. It is required that the automation config exists at the time of creating the StatefulSet.

CLOUDP-116155 Initial bootup with arbiters

---

scripts/dev/edit_cluster_config.sh

With `scripts/dev/edit_cluster_config.sh` we can easily edit the cluster config in the secret that is mounted into mongodb-agents' pods. 
It's handy when there is a need to tinker with the automation agent directly.

Tool for editing cluster config secret

---

.gitignore
controllers/mongodb_tls_test.go
docs/RELEASE_NOTES.md
pkg/kube/podtemplatespec/podspec_template.go
pkg/kube/podtemplatespec/podspec_template_test.go
test/e2e/replica_set_operator_upgrade/replica_set_operator_upgrade_test.go
test/e2e/setup/setup.go

In 0.7.3 there were changes to TLS secrets. Upgrading from 0.7.2 to 0.7.3, 0.7.4 was broken because the underlying secret in stateful set volume wasn't updated. It was because the code for updating volumes explicitly ignored any updates to volumes if they already exist, even if they contain important changes.

CLOUDP-131647: Update to stateful set ignored existing volumes

---

docs/RELEASE_NOTES.md
go.mod
scripts/dev/templates/readiness/Dockerfile.builder
scripts/dev/templates/versionhook/Dockerfile.builder

Bumped Go version to the latest 1.18.5 to address security issues.

Bumped Go version to 1.18

---

Makefile
inventories/e2e-inventory.yaml

* E2E image wasn't built for linux/amd64 on M1
* cleanup-e2e should use current $NAMESPACE for every kubectl command

Minor improvements to local testing on M1 macs

---

config/manager/manager.yaml

In the last release operator was not bumped in manager.yaml.

Fixed operator's version in manager.yaml

---

inventories/operator-inventory.yaml
pipeline.py

In the recent go version bump #1065, the operator version was still built with go 1.17. 
This patch bumps also go version for the operator's docker builder.

Bumped go version in operator-ubi docker builder

---

docs/RELEASE_NOTES.md
pkg/kube/container/containers.go

This Pull Request introduces the `allowPrivilegeEscalation=false` setting on each container-level `SecurityContext`.

CLOUDP-127632 AllowPrivilegeEscalation set to false

---

docs/deploy-configure.md

Hi @jwilliams-mongo, @mircea-cosbuc, and @irajdeep, I added a note about the optional `connectionStringSecretName` field.
[JIRA](https://jira.mongodb.org/browse/DOCSP-21766)

(DOCSP-21766): Added a note about the optional connectionStringSecretName field.

---

.action_templates/jobs/tests.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
api/v1/mongodbcommunity_types.go
cmd/readiness/main.go
test/e2e/replica_set_operator_upgrade/replica_set_operator_upgrade_test.go
test/e2e/setup/setup.go

This patch enables the operator upgrade test in the e2e suite and adds TLS and arbiter settings to the resource in the test.

CLOUDP-132091: Add TLS and arbiters to operator upgrade test

---

controllers/mongodb_tls.go
controllers/mongodb_tls_test.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go

Closes #1114 and #1054 on GH.
The issue has existed beforehand.
Yes.
#1115 Exists, however, is incomplete and is mixing the TLS validations into an (at least in my opinion) undesired place of different validations. But maybe you/we would like to actually broaden the scope of validations, happy to hear your preferred choice.

Fix validation of  references to CA certificate in TLS config

---

api/v1/mongodbcommunity_types.go
api/v1/mongodbcommunity_types_test.go
controllers/replica_set_controller.go
controllers/validation/validation.go

This PR closes closes #1055.
When `spec.security.modes` field is set to an empty array, the operator crashes. Upon inspection of the operator error log, we find that the crash happens when the operator is `Validating MongoDB.Spec` as it results in a index out of range [0] with length 0 runtime error. 
```go
func (m MongoDBCommunity) GetScramOptions() scram.Options {
ignoreUnknownUsers := true
if m.Spec.Security.Authentication.IgnoreUnknownUsers != nil {
ignoreUnknownUsers = *m.Spec.Security.Authentication.IgnoreUnknownUsers
}
authModes := m.Spec.Security.Authentication.Modes
defaultAuthMechanism := ConvertAuthModeToAuthMechanism(defaultMode)
autoAuthMechanism := ConvertAuthModeToAuthMechanism(authModes[0])
authMechanisms := make([]string, len(authModes))
for i, authMode := range authModes …
```

CLOUDP-130486 fix operator crash due to empty modes array

---

controllers/mongodb_tls.go
controllers/mongodb_tls_test.go
controllers/prometheus.go
release.json
test/e2e/feature_compatibility_version/feature_compatibility_version_test.go
test/e2e/prometheus/prometheus_test.go

This patch changes the prometheus TLS secret mount path to avoid the conflict with the MongoD server TLS certificate mount path.
closes #1127

CLOUDP-137882: Use different mount path for prometheus TLS secret

---

README.md

The https://coreos.com website seems to be down since last year. The link https://coreos.com/operators/ present in the README.md file does not work. I changed the link to point to the Kubernetes docs page detailing the concept of an operator.
closes #1156

Fix unavailable link in README.md

---

requirements.txt

CLOUDP-145867: Bump kubernetes python dependency version

---

cmd/readiness/readiness_test.go
controllers/construct/build_statefulset_test.go
controllers/replicaset_controller_test.go
pkg/util/envvar/envvars_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```

test: use `T.Setenv` to set env vars in tests

---

scripts/dev/e2e.py
test/e2e/feature_compatibility_version/feature_compatibility_version_test.go
test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_arbiter/replica_set_arbiter_test.go

- bump helm-charts: https://github.com/mongodb/helm-charts/pull/193
- bump overall test limit from 30m to 45m (tests succeeding almost take 30minutes: https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/3891209152/jobs/6641225437 vs failures: https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/3894602279/jobs/6648879374).
- removes explicit sts timeout usage at they are matching the default opts
- bumping sts test timeout from 20 to 25 as this one is one of the longest running checks (https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/3543640187/jobs/5950896967)
- add log for sts elapsed time. This could be done properly but it takes more refactoring. Most of the flaky tests are the sts checks, as they take the most time. If we think it …

[e2e] bump sts timeout, logs update, helm update 

---

Makefile
test/e2e/util/mongotester/mongotester.go

- only log connection success if attempts were more than 1, otherwise its just noisy
- add a make target to not cleanup the environment, useful for debugging broken e2e tests
- adds `options` to our go test make targets i.e. ` make e2e-telepresence test=replica_set cleanup=false option=-short`
- adds a test skip option in our testing connectivity suite. Albeit we already have the function `SkipTestIfLocal` we would need a bit more of a refactor to properly support it. I thought adding this check is small enough to not warrant the method refactor
```
> make e2e-telepresence test=replica_set cleanup=false options=-short
....
=== RUN   TestReplicaSet/AutomationConfig_has_the_correct_version
--- PASS: TestReplicaSet (189.24s)
--- PASS: TestReplicaSet/Create_MongoDB_Resource (0.01s)
--- PASS: …
```

[testing] [local] optionally skip connectivity tests

---

inventory.yaml

* Make sure that we build and use amd64 images. Even if we are building on other machines locally (m1,darwin).
* Building images i.e. for e2e tests are now independent of your current platform (`make all-images` + `make e2e-k8s test=replica_set_change_version`) and can use the image build by our machine. In my case M1

Use AMD64 platform for docker 

---

pkg/kube/statefulset/merge_statefulset_test.go
pkg/util/merge/merge_statefulset.go

Noticed an issue when the original stateful set label selectors are nil, merging with an override would always keep the label selectors `nil`. Added some unit tests for this code path as well.

Fix merging nil label selectors

---

cmd/versionhook/main.go
controllers/construct/mongodbstatefulset.go
pkg/agent/agent_readiness.go

* When checking whether our agents are ready or not we log when a Pod is not ready. There is a logging bug when the pod is not running yet. This means we are checking the goal state of a pod that does not exist yet. This will lead to the following output:
```
DEBUG   agent/agent_readiness.go:102    The Pod '' doesn't have annotation 'agent.mongodb.com/version' yet  {"ReplicaSet": "default/mdb0"}
```
*  When the pod is not around (yet) there is no goalState that needed to be checked, so we can skip that check where the wrong log came from.
*  Fixes some comments

[log] fix log output for pods that don't exist yet

---

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
pkg/authentication/scram/mock_types_test.go
pkg/authentication/scram/scram.go
pkg/authentication/scram/scram_test.go

- adds ownerref to scram secrets, we should make sure to delete them in case the CRD gets deleted
- partly related to: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1074 (which is related to scram name changes). Nevertheless, we should cleanup during removal.

 add ownerref to scram secrets

---

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
scripts/ci/config.json
scripts/dev/dev_config.py
scripts/dev/e2e.py
scripts/dev/get_e2e_env_vars.py
test/e2e/replica_set_mongod_config/replica_set_mongod_config_test.go
test/e2e/setup/setup.go
test/e2e/setup/test_config.go

- update your community `~/.community-operator-dev/config.json` with `mongodb_image_repo_url` and `mongodb_image_name`
```
{
"namespace": "mongodb",
...
"mongodb_image_name": "mongodb-enterprise-database",
"mongodb_image_repo_url": "quay.io/mongodb",
"e2e_image": "community-e2e",
...
}
```
- verify that these are sourced in our helping scripts:
```
mongodb-kubernetes-operator ❯ python scripts/dev/get_e2e_env_vars.py  | rg MONGODB_
export MONGODB_IMAGE=mongodb-enterprise-database
export MONGODB_REPO_URL=quay.io/mongodb
```
- run an e2e test which should use your local `~/.community-operator-dev/config.json` if not otherwise defined
```
make e2e-k8s test=feature_compatibility_version
```
- verify that the updated repo image is used in the sts
```
❯ k get sts mdb0 -oyaml | rg image | rg …
```

[CLOUDP-113527] make mongo image and repo configurable for e2e tests

---

controllers/mongodb_cleanup.go
controllers/mongodb_cleanup_test.go
controllers/replica_set_controller.go
controllers/validation/validation.go

closes #1074
- rely on the `lastSuccessfulConfiguration` and prepare so that it can be used during the whole reconciliation 
- add a method before finishing reconciliation, but after updating the automation config, to check for leftover resources, in this case scram secrets
- my provided unit tests
- re-create issue  #1074
- do the name change as provided in the issue
- verify with `kubectl get secrets` that the old secret got deleted
- verify given the log message in the operator i.e. 
```
2023-01-25T16:15:54.211+0100    DEBUG   controllers/mongodb_cleanup.go:19       Sucessfully cleaned up secret: another-scram-name-7-scram-credentials   {"ReplicaSet": "mongodb/example-mongodb-leak"}
```

[CLOUDP-132990] cleanup leftover resources for scram secrets

---

cmd/readiness/main.go

We panic on purpose on errors to have the information in the pod description.
But we always panic due to missing the health status file, since the file will can be missing during early of the pod startup. Making this a red herring in the describe.
```
│   Warning  Unhealthy  15m   kubelet            Readiness probe failed: panic: open /var/log/mongodb-mms-automation/agent-health-status.json: no such file │
│  or directory                                                                                                                                             │
│                                                                                                                                                           │
│ goroutine 1 [running]: …
```

remove panic of missing health status.json

---

pkg/automationconfig/automation_config_builder.go
pkg/automationconfig/automation_config_test.go

This PR closes closes #1072.
Changing the featureCompatibilityVersion to an invalid value causes all mongodb-agent containers to remain in an unready state. When a valid CR is applied in an attempt to recover state, the operator is unable to create the replica set due to the previously invalid value and the CR deployment eventually fails and has to be manually redeployed.
It is very important to resolve this issue as it greatly hurts the availability of the cluster because the entire cluster has to be deleted and then redeployed which causes a very long system downtime. This cannot be afforded as high availability is central to MongoDB’s guarantees.
```go
func (b *Builder) setFeatureCompatibilityVersionIfUpgradeIsHappening() error {
// If we are upgrading, we can't increase …
```

CLOUDP-132991 fix `fcv` format validation to prevent system downtime and irrecoverable system state

---

pkg/kube/secret/secret.go
pkg/kube/secret/secret_builder.go
pkg/kube/secret/secret_test.go

- fixes `CreateOrUpdateIfNeeded` which was comparing `secret.StringData` with `secret.Data` by converting one to the other. This does, most of the cases, not work because our internal `builder` only sets the `secret.Data` field hence making this comparison not working if we rely on fields we have set ourselves. That is the usual case
- adding tests to verify that behaviour

CLOUDP-164942 fix data comparison code and add tests

---

pkg/kube/service/service.go
pkg/util/merge/merge_service_spec.go
pkg/util/merge/merge_test.go

Fixed is a bug in `service.Merge` code that mutated Spec.Ports[0].NodePort in spec passed from the outside. 
`service.Merge` is unused in the community codebase, hence no tests here. 
Additionally, incorporated changes from another (closed) PR: #1229

Fixed possibility of mutating passed service ports in service.Merge

---

api/v1/mongodbcommunity_types.go
cmd/readiness/testdata/health-status-no-replication.json
cmd/readiness/testdata/health-status-ok-no-replica-status.json
controllers/replicaset_controller_test.go
pkg/kube/annotations/annotations.go
pkg/kube/client/client_test.go
pkg/readiness/health/health.go

- fix json readiness probe formatting.
- fix `setAnnotation(object)` to only set `annotations` to given `object` and not replace the whole object with the one backed by kubernetes. This was bugprone, especially since most of the places were relying on using calling `setAnnotation(object.DeepCopy)`.
- fixes `mongodConfig.DeepCopy` since it was not null pointer safe.

bugfix: make setAnnotation do what the signature implies

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/RELEASE_NOTES.md
docs/how-to-release.md
release.json

Release MongoDB Kubernetes Operator v0.7.9

---

pkg/automationconfig/automation_config_builder.go

In enterprise we can have image tags that already contain the `-ent` suffix. In this case we would like to be safe and support images that support `-ent` and not.

only add "ent" suffix if it does not exist in the version name already

---

inventory.yaml

We need to align the dockerfile name to be of the image repo name, since some scripts expect that

align image repo and dockerfile name

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/RELEASE_NOTES.md
docs/how-to-release.md
release.json

Charts PR: https://github.com/mongodb/helm-charts/pull/224
Internal release checklist: https://docs.google.com/document/d/1tohopsobTh56toxzn2WjqbtcMXzoRUZf06btYHshkQQ/edit
git log --left-right --graph --cherry-pick --oneline origin/release-0.8.0...v0.7.9 
```
< 1c14567 Release MongoDB Kubernetes Operator v0.8.0
< 22ada53 CLOUDP-172223 daily rebuilds support for versionhook and readiness images && making both ubi based  (#1284) <--- is in release note 
< ffc7abe Upgrade to go version 1.20 (#1287)   <--- not necessary
< c9a4933 Bump github.com/stretchr/testify from 1.8.1 to 1.8.2 (#1249)  <--- not necessary
< d1f2a26 Bump github.com/imdario/mergo from 0.3.13 to 0.3.15 (#1246)  <--- not necessary
< 247672a CLOUDP-169740 Small doc correction (#1279) <--- not necessary
< 0cdc8c5 only add ent …
```

Release MongoDB Kubernetes Operator v0.8.0

---

cmd/readiness/main.go
cmd/readiness/readiness_test.go
cmd/readiness/testdata/health-status-deadlocked-waiting-for-correct-automation-credentials.json
cmd/readiness/testdata/health-status-enterprise-upgrade-interrupted.json
cmd/readiness/testdata/health-status-error-tls.json
pkg/readiness/headless/headless.go
pkg/readiness/headless/headless_test.go
pkg/readiness/health/health.go
pkg/readiness/health/health_test.go

This Pull Request changes the core deadlock detection algorithm and replaces it with detecting Wait Steps (the steps with `isWaitStep: true`. This loosens up the way the Probe behaves and makes it less restrictive. 
The end user impact is completely opposite now. In the worst case scenario, we will report the database to be ready (instead of not ready and blocking the rollout as we've seen before). The end user experience is much better as it may experience a short outage instead of full database blackout. 
This Pull Request also introduces name refactoring and aligns it with the field names in JSON file. This way, it's less confusing when discussing this with a wider Team.
A lot of this design is related to this conversation: https://github.com/mongodb/mongodb-kubernetes-operator/pull/133 …

CLOUDP-189434 Using Wait Steps instead of risky Steps

---

pkg/readiness/headless/headless.go

Sometimes the agent is not returning IsInGoalState when mongod is scaled down. 
This change prevents the operator from being stuck and allows to progress and remove the pod from the statefulset.
If there are no plans after removing the process from automation config and IsInGoalState=false, the target version was -1 and it wasn't possible to recover automatically from this situation.

Returning ready if there are no plans in headless mode

---

config/default/kustomization.yaml
config/local_run/kustomization.yaml

**What this PR does**
This PR removes a deprecation in two kustomizations, where the field kustomize v2's  `bases` field was still used.
From the version 3 `resources` replaces both usages of child kustomizations and bases kustomizations located outside of the user kustomization directory, becoming agnostic to the location of kustomizations, and their resources are accumulated the same way.
**Additional context**
Furthermore, kustomize v3 is already two major versions behind the current stable one (v5).
There are already users of the latter version, for example,  `kubectl` v1.27 comes with the embedded kustomize v5.0.1.
Unrelated to the previous point, it seems that no `operator-sdk generate kustomize manifests` automated run is present in the codebase, and the kustomizations are not …

chore(config): remove kustomize deprecations

---

.action_templates/e2e-fork-template.yaml
.action_templates/e2e-pr-template.yaml
.action_templates/e2e-single-template.yaml
.action_templates/steps/build-and-push-development-images.yaml
.action_templates/steps/set-up-qemu.yaml
.github/workflows/e2e-dispatch.yml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
Makefile
config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/install-upgrade.md
inventories/e2e-inventory.yaml
inventories/operator-inventory.yaml
inventory.yaml
pipeline.py
pkg/automationconfig/automation_config_builder.go
scripts/ci/config.json
scripts/dev/dev_config.py
scripts/dev/e2e.py
scripts/dev/templates/Dockerfile.e2e
scripts/dev/templates/Dockerfile.template
scripts/dev/templates/operator/Dockerfile.builder
scripts/dev/templates/readiness/Dockerfile.builder
scripts/dev/templates/versionhook/Dockerfile.builder
test/e2e/setup/test_config.go

Closes #299 
The image building process will use the same dockerfile for both of architectures. The dockerfiles have been updated to accommodate for any target platform. Like before, we use sonar to build docker images, but now, sonar is used twice to build an image for both amd64 and arm64 architecture. Thus resulting in images with the suffix '-amd64' and '-arm64'. 
After building the images, the method `create_and_push_manifest` will use the created images with the architecture suffix and combine them in a manifest which is then pushed to the quay.io registry. This manifest is the final multi-arch image. In the end, the users will be able to pull the same image tag and get the appropriate image for their architecture, thus, it will work ootb for both architectures.
Here is an …

CLOUDP-82639: ARM support

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
docs/RELEASE_NOTES.md
release.json

Release MongoDB Kubernetes Operator v0.8.3

---

config/samples/external_access/cert-x509.yaml
docs/RELEASE_NOTES.md
docs/external_access.md
docs/x509-auth.md

@mircea-cosbuc and @nammn, I added the steps to enable X.509 authentication.
[JIRA](https://jira.mongodb.org/browse/DOCSP-32647)

(DOCSP-32647): Added X509 procedure.

---

.action_templates/jobs/tests.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
release.json
test/e2e/e2eutil.go
test/e2e/replica_set_enterprise_upgrade_6_7/replica_set_enterprise_upgrade_5_6_test.go
test/e2e/replica_set_operator_upgrade/replica_set_operator_upgrade_test.go

- bumping agent  and tools version to support MDB7
- adding support for MDB7
- adding a migration test from 6 to 7 (https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/6773775091/job/18409562400?pr=1422) 
- bumping default test mdb version from 6 to 7, except for operator upgrade test. There we need to use mdb below 7 because we never supported mdb7 from those operator versions

CLOUDP-209728  - add support for MDB7

---

.action_templates/jobs/setup.yaml
.action_templates/steps/build-and-push-development-images.yaml
.github/workflows/e2e-dispatch.yml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
.github/workflows/release-images.yml
.github/workflows/release-single-image.yml
Makefile
docs/contributing.md
inventories/e2e-inventory.yaml
inventories/operator-inventory.yaml
inventory.yaml
pipeline.py
release.json
scripts/ci/config.json
scripts/ci/determine_required_releases.py
scripts/ci/update_release.py
scripts/dev/dev_config.py
scripts/dev/e2e.py

- The `pipeline.py` file was refactored to reduce duplication and simplify the build process.
- Initially, there was a lot of duplication with different functions for building each image type (e.g., `build_agent_image_ubi`, `build_version_post_start_hook_image`). These shared 90% of their logic and configuration.
- The refactoring process introduced a unified function, `build_and_push_image`, to handle the building and pushing of images.
1. **Unified Build Function**:
- A single function `build_and_push_image` replaced the multiple image-building functions.
- This function centralizes the image-building process, reducing redundancy.
2. **New Argument Building Function**:
- Introduced `build_image_args` to define the build arguments passed to Sonar.
- This function starts with a default …

CLOUDP-211733 - Pipeline and build process refactoring

---

Makefile
docs/run-operator-locally.md

Local dev / documentation improvement

---

scripts/dev/templates/agent/Dockerfile.ubi

Weak dependencies for `nss_wrapper` can be safely ignored in the agent image.

CLOUDP-217175: Do not install weak dependencies for nss_wrapper

---

scripts/dev/templates/agent/Dockerfile.ubi

This Pull Request introduces `jq` to the Agent image which is going to be needed for processing logs in the Static Containers architecture. In this mode, the Agent is going to launch `agent-launcher.sh` which in turn uses `jq`.
As a subsequent step, we will be releasing `13.9.1.8594` (Cloud QA) and `107.0.0.8502-1` (OM7) versions, which contain the `operatorMode` switch in the Automation.

CLOUDP-204110 Add jq to the Agent

---

config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml
controllers/construct/mongodbstatefulset.go

Related to https://github.com/mongodb/mongodb-kubernetes-operator/issues/1443 - I couldn't reproduce the issue. But while I was at it:
1. Added default resource requirements for init-containers.
2. Added a sample to override resource requirement for init-containers.

Add default resource requirements for init-containers

---

.github/workflows/go.yml
Makefile

CLOUDP-206784: Check licenses from CI

---

pkg/agent/replica_set_port_manager.go
test/e2e/util/mongotester/mongotester.go

- making sure we wait and retry for some time until we fail the port change test. More description is in the method which has changed.

CLOUDP-155037 - ensure we are waiting for some time until all the agents have finished updating the ports

---

cmd/readiness/main.go
pkg/readiness/config/config.go
release.json

- fixes the red herring that the agent-health-status file is missing
- continue of fix: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1224, we missed a few places. This PR instead suggests to test for the file as early as possible in the code
- it can be missing, since the agent requires some time until it populates that file
- while it is still populating the probe should just return unready and it will eventually work

fix red herring in the readinessProbe

---

controllers/construct/mongodbstatefulset.go

This Pull Requests runs the upgrade hook only if it exists (and it doesn't in Static Architecture)

CLOUDP-204105 Conditionally run the upgrade hook

---

README.md

This Pull Request describes linting rules used by this project.

CLOUDP-212060 Document linting rules

---

.github/workflows/code-health.yml
.github/workflows/main.yaml
.golangci.yml
README.md
cmd/readiness/readiness_test.go
controllers/construct/mongodbstatefulset.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_arbiter/replica_set_arbiter_test.go
test/e2e/replica_set_operator_upgrade/replica_set_operator_upgrade_test.go
test/e2e/util/wait/wait.go

This Pull Request introduces gosec through golangci-lint project. As a side-effect, it removes super-linter integration.
The motivation behind integrating it this way is using a single `//nolint` comment to disable (or mark as false-positive) all linters and not using linter-specific markers (such as `nosec`).

CLOUDP-252271 Use gosec linter

---

cmd/readiness/main.go
pkg/readiness/config/config.go

example output with the console/stdout logger
```
Warning  Unhealthy  2m28s  kubelet            Readiness probe failed: {"level":"error","ts":1718279186.4724512,"msg":"health status file not avaible yet: open /var/log/mongodb-mms-automation/agent-health-status.json: no such file or directory "}
Warning  Unhealthy  83s    kubelet            Readiness probe failed: {"level":"debug","ts":1718279251.0533059,"msg":"ExpectedToBeUp: true, IsInGoalState: false, LastMongoUpTime: 1970-01-01 00:00:00 +0000 UTC"}
{"level":"info","ts":1718279251.053355,"msg":"Mongod is not ready"}
{"level":"info","ts":1718279251.0533628,"msg":"Reached the end of the check. Returning not ready."}
Warning  Unhealthy  78s  kubelet  Readiness probe failed: {"level":"debug","ts":1718279256.0862045,"msg":"ExpectedToBeUp: …
```

CLOUDP-253916 - readinessProbe: send to stdout as well, give option for compression and reduce default size

---

api/v1/mongodbcommunity_types.go
controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go

Correct argument order for AutomationAgentCommand call

---

config/manager/manager.yaml
deploy/openshift/operator_openshift.yaml
scripts/dev/templates/agent/README.md
test/e2e/replica_set_operator_upgrade/replica_set_operator_upgrade_test.go
test/e2e/setup/test_config.go

Lets ensure that all agents are on our ubi suffixed repo.
It seems that we were using a legacy repo in our master build. 
Fixes #1575

migrate all agents to ubi

---

docs/secure.md
docs/users.md

This PR changes the documentation in 2 files: 
- secure.md
- users.md
Some commands are modified because their previous versions were not producing the expected results or were incorrect:
```
helm install cert-manager jetstack/cert-manager --namespace cert-manager \ 
--create-namespace --set installCRDs=true
```
was changed to
```
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set crds.enabled=true
```
because it did not work because of the way it was split.
```
mongosh --tls --tlsCAFile /var/lib/tls/ca/ca.crt --tlsCertificateKeyFile \
/var/lib/tls/server/*.pem \ 
--host <mongodb-replica-set>.<mongodb-replica-set>-svc.<namespace>.svc.cluster.local
```
was changed to
```
mongosh "<connection-string>" --tls --tlsCAFile /var/lib/tls/ca/ca.crt …
```

Modify misleading or outdated documentation

---

controllers/mongodb_users.go

Closes #1578.
I created this PR because, in our deployment of mongodb-kubernetes-operator at NIAEFEUP, we were having trouble creating the connection string secret in a namespace that was not the one the MDBC resource was deployed to. In particular, as described in the issue, one problem that we encountered was needing to have the password secret in both namespaces (the MDBC resource namespace and the connectionStringSecretNamespace namespace) for the connection string secret to be created. The logic was changed so that the password secret is always looked up in the namespace of the MDBC resource.
As a result, the password secret now only needs to be on the namespace of the MDBC resource (as was expected by the `ensureUserResources` function).

fix: use correct namespace for password secret

---

api/v1/mongodbcommunity_types.go
controllers/mongodb_tls_test.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
pkg/automationconfig/automation_config.go
pkg/automationconfig/automation_config_secret_test.go

- This pr fixes the `LogRotate` json key to be lowerCases `logRotate`
- This pr adds auditlogrotation

fix logRotate and fix path naming add auditlogrotation 

---

.action_templates/jobs/tests.yaml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
Makefile
controllers/mongodb_cleanup.go
controllers/mongodb_cleanup_test.go
controllers/mongodb_users.go
controllers/replica_set_controller.go
docs/secure.md
docs/users.md
pkg/authentication/authentication.go
pkg/authentication/authentication_test.go
pkg/automationconfig/automation_config.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_remove_user/replica_set_remove_user_test.go

This PR adds changes that will cleanup connection string secrets after a user is removed from the resource and ensure that it will also be removed from the database.
Connection string secrets are removed by comparing the `lastAppliedSpec` with the current spec to retrieve the users that have been removed and then their corresponding connection string secrets.
Users are deleted from the database by adding a corresponding `DeletedUser` object to the `usersDeleted` field in the `auth` object of the `AutomationConfig`. This ensures the users will be deleted according to the [documentation](https://www.mongodb.com/docs/ops-manager/current/reference/cluster-configuration/#authentication:~:text=auth.-,usersDeleted,-array%20of%20objects)
The PR adds:
- 2 new methods in the …

CLOUDP-196371: Delete users removed from the resource

---

Makefile
docs/build_operator_locally.md
docs/contributing.md
docs/run-operator-locally.md
inventory.yaml
pipeline.py
scripts/dev/setup_kind_cluster.sh

This PR will improve the setup process for local development of the mongodb-kubernetes-operator. The documentation contained outdated and misleading information.  Also some problems with building images and deploying the operator were encountered because of using a local registry. This
The PR adds:
- Documentation changes to improve the local setup process
- Changes to the `Makefile`:
- Change the name of the parameter to look for the agent image in the `config.json` file to `agent_image`
- Add `--ignore-not-found` flag to `uninstall-crd` target because of errors encountered when calling this during the `make deploy` command where no crd was installed yet
- Add `$(IMG_BUILD_ARGS)` to all image building targets to allow the `--insecure` flag to be passed as a paramter
- Changes to the …

Fix inventory file and upgrade documentation

---

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
controllers/validation/validation.go
go.mod
go.sum
scripts/git-hooks/pre-commit

I have noticed a small mistake in the `controllers/validation/validation.go` file. It seems like the logic to check for collisions in the name of scram secretes was making use of the map for connection string secret names.
When a MongoDBCommunity resource was deployed with 2 users using the same scram secret name the resource would be stuck in the Pending phase
When a MongoDBCommunity resource was deployed with 2 users using the same scram secret name the resource would fail with the following error message `scram credential secret names collision, update at least one of the users: %s`
This PR adds:
- `scramSecretNameMap` instead of `connectionStringSecretNameMap` for checking collisions as the later was already used for checking connection string secrets collisions
- Changes made …

Fixing validation of collisions in scram secret's name

---

api/v1/mongodbcommunity_types.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
test/e2e/mongodbtests/mongodbtests.go

fix json naming of auditLogRotate

---

.github/workflows/release-single-image.yml
Makefile
docs/build_operator_locally.md
docs/contributing.md
docs/run-operator-locally.md
inventory.yaml
pipeline.py
scripts/dev/setup_kind_cluster.sh

This PR will improve the setup process for local development of the mongodb-kubernetes-operator. The documentation contained outdated and misleading information.  Also some problems with building images and deploying the operator were encountered because of using a local registry. This
The PR adds:
- Documentation changes to improve the local setup process
- Changes to the `Makefile`:
- Change the name of the parameter to look for the agent image in the `config.json` file to `agent_image`
- Add `--ignore-not-found` flag to `uninstall-crd` target because of errors encountered when calling this during the `make deploy` command where no crd was installed yet
- Add `$(IMG_BUILD_ARGS)` to all image building targets to allow the `--insecure` flag to be passed as a paramter
- Changes to the …

Improvements for local development setup process

---

pkg/kube/client/mocked_client.go
pkg/kube/configmap/configmap.go
pkg/kube/secret/secret.go
pkg/kube/statefulset/statefulset.go

This PR changes the way we do `CreateOrUpdate` functions. 
It was: Get the Update if exists else Create. 
For some cases after the resource was created in the same reconcile event, another execution will again hit into Create case as the informer caches weren't yet refreshed. And that resulted in errors.

Changed the order of CreateOrUpdate functions

---

cmd/readiness/main.go
release.json

Change usage of zap as described by the lib:
```
// You may change these by setting the appropriate fields in the returned
// object.
// For example, use the following to change the time encoding format:
//
//	cfg := zap.NewProductionEncoderConfig()
//	cfg.EncodeTime = zapcore.ISO8601TimeEncoder
```

CLOUDP-274724 - readinessProbe: use human readable timestamps instead

---

test/e2e/replica_set_custom_role/replica_set_custom_role_test.go
test/e2e/setup/setup.go
test/e2e/util/mongotester/mongotester.go

from test
extra elements in list A:
([]interface {}) (len=1) {
(automationconfig.CustomRole) {
Role: (string) (len=30) "MongodbAutomationAgentUserRole",
DB: (string) (len=5) "admin",
Privileges: ([]automationconfig.Privilege) (len=1) {
(automationconfig.Privilege) {
Resource: (automationconfig.Resource) {
DB: (*string)(<nil>),
Collection: (*string)(<nil>),
AnyResource: (bool) true,
Cluster: (bool) false
},
Actions: ([]string) (len=1) {
(string) (len=22) "bypassDefaultMaxTimeMS"
}
}
},
Roles: ([]automationconfig.Role) {
},
AuthenticationRestrictions: ([]automationconfig.AuthenticationRestriction) <nil>
}
}
https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/12671524133/job/35384225989#step:13:314
its passing now: https://github.com/mongodb/mongodb-kubernetes-operator/actions …

fix tests - adding missing role, increase timeout

---

.github/CODEOWNERS
.github/dependabot.yml

Updates `dependabot.yml` and `CODEOWNERS` to fix issue:
```
Dependabot tried to add @slaskawi, @lsierant, @mircea-cosbuc, @nammn and @Julien-Ben as reviewers to this PR, but received the following error from GitHub:
POST https://api.github.com/repos/mongodb/mongodb-kubernetes-operator/pulls/1657/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the mongodb/mongodb-kubernetes-operator repository. // See: https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request
```

Update dependabot and CODEOWNERS file

---

.action_templates/steps/cancel-previous.yaml
.action_templates/steps/checkout-fork.yaml
.action_templates/steps/checkout.yaml
.action_templates/steps/quay-login.yaml
.action_templates/steps/set-run-status.yaml
.action_templates/steps/set-up-qemu.yaml
.action_templates/steps/setup-and-install-python.yaml
.github/workflows/close-stale-issues.yml
.github/workflows/code-health.yml
.github/workflows/comment-release-pr.yml
.github/workflows/e2e-dispatch.yml
.github/workflows/e2e-fork.yml
.github/workflows/e2e.yml
.github/workflows/go.yml
.github/workflows/kubelinter-check.yml
.github/workflows/main.yaml
.github/workflows/release-images.yml
.github/workflows/release-single-image.yml

actions/cache@v2 is now removed and fails CI. While updating `actions/cache@v2` I also bumped other GH actions to the latest versions.

Bump gh actions

---

controllers/mongodb_tls.go
controllers/prometheus.go

`unusedparams` complains about unused args in several places:
```
unused parameter: mdb
```

Clean up unused args

---

cmd/manager/main.go
controllers/construct/build_statefulset_test.go
controllers/construct/mongodbstatefulset.go
controllers/mongodb_cleanup_test.go
controllers/mongodb_tls_test.go
controllers/replica_set_controller.go
controllers/replicaset_controller_test.go
test/e2e/replica_set_enterprise_upgrade/replica_set_enterprise_upgrade.go
test/e2e/setup/test_config.go

This will help with code reusability.

CLOUDP-302068: Refactoring: propagate env vars via parameters

---

api/v1/mongodbcommunity_types.go
controllers/construct/mongodbstatefulset.go
controllers/replica_set_controller.go
test/e2e/mongodbtests/mongodbtests.go
test/e2e/replica_set_recovery/replica_set_recovery_test.go
test/e2e/replica_set_scale/replica_set_scaling_test.go
test/e2e/replica_set_scale_down/replica_set_scale_down_test.go
test/e2e/statefulset_delete/statefulset_delete_test.go

CLOUDP-302068: Remove annotations arg from GetMongoDBVersion

---

.github/dependabot.yml

We compile and release with the lowest API we support currently, so there is no reason to create bumps for controller-runtime.

[dependabot] Ignore k8s api dependencies bumps

---

LICENSE.md

Changed "repo" to "repository" for clarity and formality.

Changed "repo" to "repository" for clarity and formality.
