go.mod, go.sum, pkg/controller/mongodb/mongodb_controller.go, pkg/kube/statefulset/statefulset.go, pkg/kube/statefulset/statefulset_builder.go, pkg/kube/statefulset/statefulset_test.go
@chatton this is not finished but I would appreciate a look :)
=> Initial import of StatefulSet objects.

deploy/crds/mongodb.com_mongodbs_crd.yaml, pkg/apis/mongodb/v1/mongodb_types.go, pkg/apis/mongodb/v1/mongodb_types_test.go, pkg/automationconfig/automation_config.go, pkg/automationconfig/automation_config_builder.go, pkg/automationconfig/automation_config_test.go, pkg/controller/mongodb/mongodb_controller.go, test/e2e/e2eutil.go
This PR adds `featureCompatibilityVersion` as a field to the MongoDB resource.
=> CLOUDP-59502: Configure FCV

.evergreen.yml, cmd/testrunner/main.go, scripts/ci/build_and_push_image.sh, scripts/ci/run_test.sh, scripts/dev/dockerfile_generator.py, scripts/dev/e2e.py
=> CLOUDP-62533: Build pre-stop image

.evergreen.yml, test/e2e/e2eutil.go, test/e2e/feature_compatibility_version/feature_compatibility_version_test.go, test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go, test/e2e/replica_set/replica_set_test.go, test/e2e/replica_set_change_version/replica_set_test.go, test/e2e/replica_set_multiple/replica_set_multiple_test.go, test/e2e/replica_set_readiness_probe/replica_set_readiness_probe_test.go, test/e2e/replica_set_scale/replica_set_scaling_test.go
Added `replica_set_multiple` tests that verifies that 2 resources can be created at the same time.
=> E2E for multiple resources

README.md, architecture.md, contributing.md, requirements.txt, scripts/ci/run_unit_tests.sh, scripts/dev/dockerutil.py, scripts/dev/e2e.py, scripts/dev/setup_kind_cluster.sh
=> Dev start guide

pkg/controller/mongodb/mongodb_controller.go, test/e2e/e2eutil.go, test/e2e/mongodbtests/mongodbtests.go, test/e2e/replica_set/replica_set_test.go
* [] Have you opened an Issue before filing this PR?
=> Cloudp 62906 set owner reference

README.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-10428)
This PR:
- Moves the logo to the right so it doesn't disrupt the information flow
- Creates a TOC for the readme
- Aligns the headings with our other MDB docs
- Adds the procedures for upgrading the Community Operator
- Adds the procedures for upgrading the MDB version/FCV of MongoDB resources.
=> (DOCSP-10428): Upgrade procedures

README.md, agent/Dockerfile, deploy/crds/mongodb.com_mongodb_crd.yaml, deploy/crds/mongodb.com_v1_mongodb_cr.yaml, deploy/operator.yaml, pkg/apis/mongodb/v1/mongodb_types.go
The images have been pushed to the following repos/locations
* *Agent*: quay.io/mongodb/mongodb-agent:10.13.0.6199-1
* *Pre Stop hook*: quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.0
* *Operator*: quay.io/mongodb/mongodb-kubernetes-operator:0.0.5
=> Release 0.0.5

pkg/controller/mongodb/mongodb_controller.go, pkg/controller/mongodb/replicaset_controller_test.go, pkg/kube/client/client.go
closes #41 
* [] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
=> CLOUDP-62351: update service

pkg/controller/mongodb/mongodb_controller.go
=> CLOUDP-64702: fix status log message

README.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-10429)
[Staging](https://github.com/melissamahoney-mongodb/mongodb-kubernetes-operator/blob/DOCSP-10429/README.md#supported-features)
Question: Are we sure we want to include the "Planned Features"? I just don't want us to commit to something now that we end up not doing.
=> (DOCSP-10429): Add supported features

scripts/dev/build_and_deploy_operator.py, scripts/dev/e2e.py, scripts/dev/k8sutil.py
=> CLOUDP-64640: fix deploy operator

pkg/automationconfig/automation_config.go, pkg/automationconfig/automation_config_builder.go, pkg/automationconfig/automation_config_test.go, pkg/controller/mongodb/mongodb_controller.go, pkg/controller/mongodb/replicaset_controller_test.go, test/e2e/mongodbtests/mongodbtests.go, test/e2e/replica_set/replica_set_test.go, test/e2e/replica_set_change_version/replica_set_test.go, test/e2e/replica_set_multiple/replica_set_multiple_test.go, test/e2e/replica_set_readiness_probe/replica_set_readiness_probe_test.go, test/e2e/replica_set_scale/replica_set_scaling_test.go
=> CLOUDP-64701: ensure automation config version bump

scripts/dev/setup_kind_cluster.sh
[kind 0.8](https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0) changed the way kind sets up networking. Previously, the kind container would be attached to the default Docker bridge network and our registry container would be attached to that by default as well. With 0.8, kind now creates its own network called `kind` which breaks our script as our registry can no longer be reached.
This PR fixes the issue by creating the `kind` network before kind does so itself and attaching the registry to that on creation. These changes are not backwards compatible and will require an update.
=> Fix broken setup script for kind 0.8

deploy/operator.yaml
=> Release v0.0.7

scripts/dev/dump_diagnostic.py
Quick fix to a wrong formatting issue that made the code_health task fail
=> fixed black formatting

test/e2e/mongodbtests/mongodbtests.go
=> reintroduced test call

pkg/kube/client/client.go
Fixed bug where DeleteSecret was actually trying to delete a Service of the given name.
=> Fix Delete Secret

.evergreen.yml, scripts/ci/build_and_push_image.sh, scripts/dev/templates/Dockerfile.template
The current images weren't being configured to expire. We have no need for the images created during our E2E testing after the tests have ended.
=> Configure Expiration Date on CI images

contributing.md
=> Fix broken link in Contributing page

pkg/controller/mongodb/mongodb_tls.go, pkg/controller/mongodb/mongodb_tls_test.go
Previously the operator assumed that there would be a single newline at the end of the certificate, otherwise the combined certificate-key would not be a valid PEM file. This PR improves the handling of newlines by always trimming them before combining the certificate and key with a single newline in between. This should result in a valid PEM file no matter how the user formatted their certificate and key.
=> CLOUDP-68630: Fix issue with missing newlines in certificate

deploy/crds/mongodb.com_v1_mongodb_tls_cr.yaml, deploy/operator.yaml
=> Release v0.1.0

README.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-11347)
=> (DOCSP-11347): Document TLS configuration for Community Operator

contributing.md
=> Fixed outdated config.json

agent/Dockerfile, deploy/crds/mongodb.com_mongodb_crd.yaml, deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml, deploy/operator.yaml, pkg/apis/mongodb/v1/mongodb_types.go, pkg/controller/mongodb/replica_set_controller.go, pkg/kube/container/container_test.go, pkg/kube/container/containers.go, pkg/kube/podtemplatespec/podspec_template.go, pkg/kube/podtemplatespec/podspec_template_test.go, pkg/util/contains/contains.go, pkg/util/envvar/envvars.go
Our arbitrary StatefulSet Spec merging was not working correctly when attempting to add additional Environment Variables, this PR fixes this issue.
=> CLOUDP-69289: Fix custom StatefulSet spec merging of Env Vars

deploy/operator.yaml
=> Release Operator v0.1.1

deploy/operator.yaml, release.json
=> CLOUDP-70200: Release Community Operator v0.2.0

deploy/crds/mongodb.com_v1_mongodb_scram_cr.yaml
Small example to show how to configure a user password with a SCRAM user
=> Add password example

pkg/controller/mongodb/replicaset_controller_test.go, pkg/controller/mongodb/testdata/custom_storage_class.yaml
closes #61
closes #126 
Add unit test for StorageClass
=> Added Unit Test for StorageClass

pkg/controller/mongodb/replicaset_controller_test.go, pkg/controller/mongodb/testdata/custom_storage_class.yaml, pkg/controller/mongodb/testdata/tolerations_example.yaml, pkg/kube/podtemplatespec/podspec_template.go
=> Correctly Merge Tolerations

scripts/dev/dump_diagnostic.py, scripts/dev/k8s_request_data.py
Cherry picked [this commit](https://github.com/mongodb/mongodb-kubernetes-operator/pull/119/commits/b3a31878a35f4df435c5cb81e589ac60ab5ffff5)
=> Read From Secret instead of ConfigMap

README.md, deploy/operator_openshift.yaml
=>  CLOUDP-69083: added instruction on how to deploy on OpenShift

build/bin/entrypoint, build/bin/user_setup, scripts/git-hooks/pre-commit
This should hopefully stop the linting errors from the Github Action
=> Fix linting errors in bash

cmd/testrunner/main.go, deploy/operator.yaml, dev_notes/how-to-release.md
=> Release v0.2.1

pkg/kube/podtemplatespec/podspec_template.go, pkg/kube/podtemplatespec/podspec_template_test.go
=> Adds securityContext to PodSpec builder

cmd/testrunner/main.go, scripts/dev/release_image.py
It looks like there was an issue with the allowed arguments in the release script
=> Fix release script

.gitignore, pkg/controller/mongodb/replica_set_controller.go, pkg/kube/client/client.go, pkg/kube/statefulset/statefulset.go
This PR updates the "UpdateStatefulSet" function to return the updated value. This is currently going to be used in the enterprise operator.
=> Updated function to return updated StatefulSet

docs/build_operator_locally.md, docs/contributing.md
This PR adds a bit more information on how to develop locally.
We will review this docs as we test them out as new devs test them.
=> Fix onboarding docs

agent/Dockerfile, deploy/openshift/operator_openshift.yaml, deploy/operator.yaml
=> Release Community Operator v0.2.2

docs/install-upgrade.md
Fix typo in crd install command
* [ n/a] Have you opened an Issue before filing this PR?
* [ n/a] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ n/a] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ n/a] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Fix typo in crd install command

pkg/automationconfig/automation_config.go, pkg/automationconfig/automation_config_builder.go, pkg/controller/mongodb/replica_set_controller.go
=> Remove tools configuration

deploy/kustomization.yaml, deploy/openshift/operator_openshift.yaml, deploy/operator/operator.yaml
=> Release v0.3.0

docs/deploy-configure.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-12497)
Based on ticket, added section to docs/deploy-configure.md describing how to scale replica sets. Added note that it might take the operator several minutes to remove the statefulset replicas for removed members.
Also moved the `Deploy Replica Sets on OpenShift` section. Current placement orphans the FCV Example section from its parent.
=> (DOCSP-12497): scale a replica set

README.md
=> link to mongodb live talks

.evergreen.yml
Test is temporarily being disabled until resolved in [CLOUDP-76190](https://jira.mongodb.org/browse/CLOUDP-76190)
=> Temporarily disable flakey test

pkg/controller/mongodb/replica_set_controller.go
See JIRA issue: [CLOUDP-78857](https://jira.mongodb.org/browse/CLOUDP-78857)
=> CLOUDP-78857: Log StatefulSet not found after creation as info

pkg/kube/statefulset/merge_spec.go, pkg/kube/statefulset/merge_spec_test.go, pkg/kube/statefulset/statefulset.go
This PR is the first part in a set of PRs that will add custom merging logic for merging StatefulSets.
=> CLOUDP-80014: refactor stateful set merging 1

.evergreen.yml, cmd/manager/main.go, cmd/testrunner/main.go, deploy/clusterwide/role.yaml, deploy/clusterwide/role_binding.yaml, go.sum, pkg/util/generate/generate.go, scripts/ci/run_test.sh, scripts/dev/e2e.py, test/e2e/e2eutil.go, test/e2e/feature_compatibility_version/feature_compatibility_version_test.go, test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go, test/e2e/mongodbtests/mongodbtests.go, test/e2e/replica_set/replica_set_test.go, test/e2e/replica_set_change_version/replica_set_test.go, test/e2e/replica_set_cross_namespace_deploy/replica_set_cross_namespace_deploy_test.go, test/e2e/replica_set_mongod_config/replica_set_mongod_config_test.go, test/e2e/replica_set_multiple/replica_set_multiple_test.go, test/e2e/replica_set_readiness_probe/replica_set_readiness_probe_test.go, test/e2e/replica_set_scale/replica_set_scaling_test.go, test/e2e/replica_set_scale_down/replica_set_scale_down_test.go, test/e2e/replica_set_tls/replica_set_tls_test.go, test/e2e/replica_set_tls_rotate/replica_set_tls_rotate_test.go, test/e2e/replica_set_tls_upgrade/replica_set_tls_upgrade_test.go, test/e2e/setup/setup.go, test/e2e/statefulset_arbitrary_config/statefulset_arbitrary_config_test.go, test/e2e/statefulset_arbitrary_config_update/statefulset_arbitrary_config_update_test.go, test/e2e/util/mongotester/mongotester.go, test/e2e/util/mongotester/mongotester_test.go
This PR adds support for cross-namespace deployments.
=> CLOUDP-78303: Support cross-namespace deployments

requirements.txt, scripts/dev/build_and_deploy_operator.py, scripts/dev/dockerfile_generator.py, scripts/dev/dump_diagnostic.py, scripts/dev/e2e.py, scripts/dev/release_image.py
All code changes are a result of using the new black formatter version.
=> Updated black version

pkg/kube/container/containers.go, pkg/util/merge/merge.go, pkg/util/merge/merge_test.go
=> CLOUDP-80014: Refactor Merging Strategy - VolumeMounts, VolumeDevices, Envs, Resources

pkg/kube/container/containers.go, pkg/util/merge/merge.go, pkg/util/merge/merge_test.go
=> CLOUDP-80014: Refactor Merging - Probes, Security Context & LifeCycle

requirements.txt
Context: https://github.com/yaml/pyyaml/issues/478#issuecomment-763975543
Let's see if this fixes the Github Actions failure.
The stuff needed for python is installed through `requirements.txt`:  https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/.github/workflows/main.yaml#L47
* [n/a ] Have you opened an Issue before filing this PR?
* [n/a] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [n/a] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Fix Github Actions failure

dev_notes/how-to-release.md, dev_notes/release-notes-template.md
Add template file for release notes.
=> Release notes template

pkg/kube/podtemplatespec/podspec_template.go, pkg/kube/podtemplatespec/podspec_template_test.go, pkg/util/merge/merge.go, pkg/util/merge/merge_ephemeral_container.go, pkg/util/merge/merge_podtemplate_spec.go, pkg/util/merge/merge_test.go
=> Refactor Merging Strategy #6

deploy/openshift/operator_openshift.yaml, deploy/operator/operator.yaml, release.json
=> Release v0.4.0

docs/deploy-configure.md, docs/secure.md, docs/users.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-14230)
Updated docs examples based on #294
=> (DOCSP-14230): update kind in docs examples

README.md, deploy/openshift/operator_openshift.yaml, deploy/operator/operator.yaml, dev_notes/dev-quick-start.md, release.json
=> Release v0.5.0

docs/deploy-configure.md
=> Fix reference to old crd name in docs

deploy/crds/mongodb.com_v1_mongodbcommunity_cr.yaml, deploy/crds/mongodb.com_v1_mongodbcommunity_custom_role.yaml, deploy/crds/mongodb.com_v1_mongodbcommunity_openshift_cr.yaml, deploy/crds/mongodb.com_v1_mongodbcommunity_tls_cr.yaml, docs/deploy-configure.md
=> CLOUDP-81292: Remove placeholder passwords from crs

dev_notes/dev-quick-start.md, docs/build_operator_locally.md
=> Update build locally and dev quick start docs

APACHE2
=> add copyright

.github/dependabot.yml
=> CLOUDP-82737: add dependabot

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, docs/build_operator_locally.md, docs/contributing.md, docs/deploy-configure.md, docs/install-upgrade.md, release.json
=> Release v0.5.1

.evergreen.yml
We were stuck at 4 while our tasks were <8, now we can bump it (the max values is 10, let's keep it at half the number of tasks for now)
=> Increase max_hosts

pkg/authentication/scram/scram.go
=> Add additional context with scram errors

CODE_OF_CONDUCT.md, SECURITY.md
=> Added code of conduct and Security

docs/install-upgrade.md
References correct files to install operator in cluster-wide mode.
closes #379
=> CLOUDP-84855: Improved clusterwide install docs.

pkg/kube/container/container_test.go, pkg/kube/container/containers.go
This PR adds a configuration function for the Startup Probe.
=> Added function for startup probe

agent/Dockerfile.ubi, config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, release.json, scripts/ci/build_and_push_agent_image.sh, test/e2e/setup/test_config.go
=> Changed agent version

controllers/construct/mongodbstatefulset.go
This would make it much cleaner the STS construction in enterprise
=> Export full automation command

.evergreen.yml, inventory.yaml, pipeline.py, scripts/dev/dockerfile_generator.py, scripts/dev/dockerfiles/Dockerfile.versionhook
This PR adds the readiness probe and version upgrade hook init containers to the inventory.yaml file.
=> CLOUDP-83092: Add init container images to inventory file

README.md
Related to this comment: https://github.com/mongodb/mongodb-kubernetes-operator/issues/460#issuecomment-836246971
=> Add notes regarding enterprise and community operator docs.

Makefile, config/default/kustomization.yaml
=> Use namespace specified in config.json for operator deployment

cmd/manager/main.go
i. Use dedicated logging instead of os.exit
ii. Use pre-existing logger in main
Now when the operator enters `crashloopbackoff` because of missing CRD it logs the following line instead of failing silently.
```
2021-05-13T15:45:07.072Z	FATAL	manager/main.go:108	Unable to start manager: no matches for kind "MongoDBCommunity" in version "mongodbcommunity.mongodb.com/v1"
main.main
/workspace/cmd/manager/main.go:108
```
=> Logging improvement in manager main method

pkg/automationconfig/automation_config_builder.go
This PR adds the required "enterprise" module if the version of MongoDB specified uses the enterprise format.
=> Enterprise only

test/e2e/feature_compatibility_version_upgrade/feature_compatibility_version_upgrade_test.go
There was an error with this test where it attempted to create setup resources multiples times and failed as a result.
=> Fix FCV Upgrade Test

Makefile, dev_notes/dev-quick-start.md, scripts/dev/setup_kind_cluster.sh
Some fixes to dev start scripts. See comments inlined
=> Some fixes in dev-start scripts/docs

README.md
=> Fix wrong header in  README.md

scripts/dev/e2e.py
=> Create role/rolebinging in namespace configured in config.json and create namespace if it doesn't exist.

api/v1/mongodbcommunity_types.go, controllers/replica_set_controller.go, controllers/replicaset_controller_test.go, test/e2e/mongodbtests/mongodbtests.go, test/e2e/replica_set/replica_set_test.go, test/e2e/util/mongotester/mongotester.go
=> Cloudp 76562: support srv records

Makefile
Part of cleanups before interns join
=> Remove unused bundle target from Makefile

docs/install-upgrade.md
=> add detailed upgrade steps

test/e2e/mongodbtests/mongodbtests.go
This PR removes some dead code from our E2E tests.
=> Remove Dead Code

docs/deploy-configure.md, docs/secure.md, docs/users.md
=> Fix apiVersion in docs files

docs/RELEASE_NOTES.md, scripts/dev/templates/agent/Dockerfile.ubuntu
=> CLOUDP-57889: Update agent to Ubuntu 20.04

scripts/ci/add_supported_release.py
Fixes a problem with the add_supported_release that won't be able to add new versions to mongodb-agent.
=> Fixes query to find existing releases.

docs/contributing.md
Fixing the Enterprise MongoDB Kubernetes Operator github link in contributing.md
=> Fixing the Enterprise MongoDB Kubernetes

docs/deploy-configure.md
@jwilliams-mongo, I added the `spec.security.authentication.ignoreUnknownUsers` field.
[JIRA](https://jira.mongodb.org/browse/DOCSP-16456)
=> (DOCSP-16456): Added new field.

.github/workflows/e2e-dispatch.yml, .github/workflows/e2e.yml, Makefile, scripts/dev/run_e2e_gh.sh
This PR adds a workflow that we can trigger manually to run a single test.
Note: Until the workflow is merged into master it is not possible to actually trigger it! I will test it once merged and create a follow up PR if necessary.
=> Add Manually Triggerable E2E Workflow

docs/deploy-configure.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-16408)
Closes #452 
* [ x] Have you opened an Issue before filing this PR?
* [x ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ x] Have you signed all of your commits?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ x ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> (DOCSP-16408): Expose connection string for deployments for easy of use

release.json
=> bump release.json

scripts/dev/e2e.py
We discovered this while setting up E2E tests with @FlorentinaSimlinger
=> Create Namespace for e2e if it doesn't exist

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml
default branch (https://github.com/mongodb/mongodb-kubernetes-operator/tree/master)
<details>
<summary>Details: </summary>
<details>
<summary><em>add path</em></summary>
```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/bin
```
</details>
<details>
<summary><em>python scripts/ci/update_release.py</em></summary>
</details>
</details>
<details>
<summary>Changed 2 files: </summary>
- config/manager/manager.yaml
- deploy/openshift/operator_openshift.yaml
</details>
<hr>
[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)
=> Release MongoDB Kubernetes Operator v0.6.2

.github/workflows/e2e.yml, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, docs/contributing.md
=> Updated e2e.yml to include workflow_dispatch

.github/workflows/remove-label.yml, config/rbac/role.yaml, deploy/clusterwide/role.yaml, docs/RELEASE_NOTES.md
=> CLOUDP-82702: Reduce operator role permissions

.action_templates/e2e-fork-template.yaml, .action_templates/e2e-pr-template.yaml, .action_templates/e2e-single-template.yaml, .action_templates/jobs/display-github-context.yaml, .github/workflows/e2e-dispatch.yml, .github/workflows/e2e-fork.yml, .github/workflows/e2e.yml
Dump github context in github actions
=> Add github context action

pkg/kube/service/service.go
=> Move the CreateorUpdateService to community repo.

.action_templates/e2e-pr-template.yaml, .github/workflows/e2e.yml
Always run E2E tests when manually triggered.
=> Always Run on Workflow Dispatch

.github/workflows/release-single-image.yml, release.json
Updates to latest agent image supporting OM50.
- I have added AWS_CREDS to be able to push to S3
=> CLOUDP-94049: Updates agent image to latest.

api/v1/mongodbcommunity_types.go, controllers/mongodb_users.go, controllers/replica_set_controller.go
=> CLOUDP-94119: Do not mark the CR as failed on secret absence, it could be deleted at later stage after when scram is set

Makefile, config/manager/kustomization.yaml
Make deploy was broken on the master branch. 
Found a way to fix it with the help of @chatton
=> Fixing the make deploy command

config/samples/external_access/cert-manager-certificate.yaml, config/samples/external_access/cert-manager-issuer.yaml, config/samples/external_access/external_services.yaml, config/samples/external_access/mongodb.com_v1_mongodbcommunity_cr.yaml, docs/external_access.md
Tested split horizon, added docs and example manifests for deploying MongoDB with external access.
=> CLOUDP-90359: Tested split-horizon and added docs

config/manager/manager.yaml, config/rbac/role.yaml, config/rbac/role_binding_database.yaml, config/rbac/role_database.yaml, config/rbac/service_account_database.yaml, deploy/clusterwide/role_binding.yaml, deploy/openshift/operator_openshift.yaml
fixes: https://github.com/mongodb/mongodb-kubernetes-operator/issues/639
=> Don't hardcode namespace in manager -- users can deploy in their own namespaces.

config/samples/mongodb.com_v1_mongodbcommunity_cr_podantiaffinity.yaml
This PR adds a sample of a custom resource where podAntiAffinity is used.
=> CLOUDP-89479: PodAntiAffinity sample CR 

api/v1/mongodbcommunity_types.go, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, controllers/mongodb_status_options.go, controllers/mongodb_status_options_test.go, controllers/replica_set_controller.go, deploy/e2e/service_account.yaml, scripts/dev/e2e.py, test/e2e/mongodbtests/mongodbtests.go, test/e2e/replica_set_recovery/replica_set_recovery_test.go, test/e2e/replica_set_scale/replica_set_scaling_test.go, test/e2e/replica_set_scale_down/replica_set_scale_down_test.go
This PR adds Version to the Status field and correspondingly changes the tests.
=> CLOUDP-95181: version is missing

pkg/kube/secret/secret.go
=> Move copy secret(from one cluster to another) functionality to community codebase.

Makefile
=> Correcting a small fix

pkg/kube/statefulset/statefulset.go
To be used in MC sts construction
=> Add WithAnnotations and WithVolumeClaimTemplates method to Statefulset construction

pkg/kube/statefulset/statefulset.go
=> Added options to CreateVolumeFromConfigMap

docs/install-upgrade.md
=> fix deployment scopes link in install doc

.github/config_files/config_lint.yaml, .github/config_files/config_lint_clusterwide.yaml, .github/config_files/config_lint_openshift.yaml, .github/workflows/kubelinter-check.yml
Context here: https://mongodb.slack.com/archives/CGLP6R2PQ/p1632477637288000
=> Use new kubelinter action version and pin kubelinter

pkg/kube/statefulset/statefulset.go, pkg/kube/statefulset/statefulset_test.go
=> Changed WithAnnotations to merge instead of setting

pkg/util/merge/merge.go
=> Added merge.StringToBoolMap

pkg/helm/helm.go, test/e2e/mongodbtests/mongodbtests.go, test/e2e/setup/setup.go
Uses latest helm-chart, where CRDs has been separated into own Chart.
=> Uses latest version of helm-charts.

Makefile
Makefile now respects `MONGODB_COMMUNITY_CONFIG` env variable.
=> Makefile uses configured local config.

controllers/construct/mongodbstatefulset.go
=> Read agent API Key from file on startup

pkg/kube/client/client.go
=> Separate Kube Secret Client

pkg/authentication/scram/mock_types_test.go, pkg/automationconfig/automation_config_secret_test.go, pkg/kube/client/client.go, pkg/kube/secret/secret.go, pkg/kube/secret/secret_test.go
This reverts commit 316be0034c8a8ae4324257b3fe84c2425555022d.
=> Revert "Pass optional string in different methods (#794)"

pkg/authentication/scram/scram.go
This logic is called from enterprise
=> Configure SCRAM secret exist to check Vault as well

pkg/kube/secret/secret.go
This change enabled SCRAM for AppDB on enterprise with vault
=> Configure secret check error

api/v1/mongodbcommunity_types.go, test/e2e/e2eutil.go
=> CLOUDP-107433: correctly default to admin db

config/samples/arbitrary_statefulset_configuration/mongodb.com_v1_hostpath.yaml
Example requested in the (now closed due to inactivity) issue #202
=> CLOUDP-78291: host example

.github/workflows/main.yaml
Uses `--namespace` instead of `--set namespace`.
=> CLOUDP-105007: Bumps helm-charts.

docs/architecture.md, docs/build_operator_locally.md, docs/external_access.md, docs/install-upgrade.md
=> Consistency and fixes in docs

deploy/clusterwide/role_binding.yaml
Closes #834
#820 will fix the same issue, but I don't know if/when that will be merged.
=> Cluster-wide deployment: Fix kustomize compatibility

config/samples/mongodb.com_v1_mongodbcommunity_additional_mongod_config_cr.yaml
=> CLOUDP-109125: Add sample for additional mongod config

docs/README.md, docs/architecture.md, docs/contributing.md, docs/deploy-configure.md, docs/install-upgrade.md, docs/release-notes-template.md, docs/secure.md, docs/users.md
@rodrigovalin, I updated "MongoDB resource" to " MongoDBCommunity resource".
[JIRA](https://jira.mongodb.org/browse/DOCSP-16543
)
=> (DOCSP-16543): Changed MongoDB resource to MongoDBCommunity resource.

docs/external_access.md
=> Add example for setting multiple horizons

.github/workflows/go.yml, go.mod, pipeline.py, release.json, scripts/dev/templates/readiness/Dockerfile.builder, scripts/dev/templates/versionhook/Dockerfile.builder
=> Bump go version to 1.17, using 1.17.6 for readiness probe for CVE fixes

inventory.yaml
=> Fix agent context image input

requirements.txt
=> Pin markupsafe to 2.0.1

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, deploy/clusterwide/role-for-binding.yaml
closes #831
Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>
=> Support Service Binding Operator

docs/install-upgrade.md
=> CLOUDP-108002: Mention to install the CRD from a specific git tag

controllers/replica_set_controller.go
A service will be updated on each reconciliation. Needed if Prometheus is added to a MongoDB resource with no Prometheus beforehand.
=> Updates Service if adding Prometheus.

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, pkg/automationconfig/automation_config.go
=> Adds Hash/Salt password fields.

LICENSE.md
Closes https://github.com/mongodb/mongodb-kubernetes-operator/issues/938
=> Add link to agent license

.github/workflows/code-health.yml, requirements.txt
Related to the CI failures: https://github.com/psf/black/issues/2964
=> Update black version to 22.3.0

README.md, SECURITY.md, api/v1/mongodbcommunity_types.go, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, docs/architecture.md, docs/deploy-configure.md, docs/secure.md, docs/users.md
* [ x] Have you opened an Issue before filing this PR?
* [ x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> DOCSP-20364: update docs URLs based on new locations

pkg/kube/persistentvolumeclaim/pvc.go
Will be used from enterprise to modify PVC labels
=> Add WithLabels method to pvc modify methods

api/v1/mongodbcommunity_types.go, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
Adds default value to user database: "admin". Fixes a failing E2E test.
=> Adds default name to user database.

docs/install-upgrade.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-18725)
=> (DOCSP-18725) Adds sections for instructions to install with HELM

inventory.yaml
=> CLOUDP-114697: Pushes dockefiles to correct path

docs/deploy-configure.md
Updates documentation on arbiters, making it clear that `members` + `arbiters` is the resulting amount of mongods.
=> Updates documentation on arbiters.

release.json, scripts/dev/templates/readiness/Dockerfile.builder
=> Use amd64 GOARCH for readiness probe image

docs/deploy-configure.md, docs/install-upgrade.md
Updates missing entries in table of content sections in:
* docs/deploy-configure.md
* docs/install-upgrade.md
=> Updates table of content in docs

Makefile
=> Use already installed helm from PATH in Makefile

cmd/readiness/main.go, controllers/mongodb_tls.go, controllers/mongodb_tls_test.go, pkg/readiness/headless/headless.go
=> Readiness Probe: Check for acVersion file only if it is present

controllers/construct/mongodbstatefulset.go, pkg/automationconfig/automation_config.go
=> Do not tail mongodb.log which is not present in the container

.github/CODEOWNERS
=> Added slaskawi to code owners

api/v1/mongodbcommunity_types_test.go, cmd/readiness/main.go, cmd/versionhook/main.go, controllers/replicaset_controller_test.go, pkg/agent/agent_readiness.go, pkg/automationconfig/automation_config_test.go, pkg/kube/statefulset/merge_statefulset_test.go, pkg/readiness/config/config.go, pkg/readiness/headless/headless.go, test/e2e/replica_set_mount_connection_string/replica_set_mount_connection_string_test.go
Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>
fixing #1027
=> remove io/ioutil and fmt imports with Goimports

scripts/dev/setup_kind_cluster.sh
This Pull Request introduces the force option to the kind setup script. It's helpful for quick restarting the setup.
=> Add force option to setting up kind

pkg/automationconfig/automation_config.go
=> Add back "SetSystemLog" to be used for AppDB

cmd/versionhook/main.go, controllers/mongodb_tls.go, controllers/prometheus.go, controllers/replica_set_controller.go, controllers/replicaset_controller_test.go, controllers/validation/validation.go, go.mod, pkg/authentication/scram/scram.go, pkg/authentication/scramcredentials/scram_credentials.go, pkg/automationconfig/automation_config_builder.go, pkg/kube/configmap/configmap.go, pkg/kube/secret/secret.go, pkg/kube/statefulset/statefulset_builder.go, pkg/util/state/statemachine.go, pkg/util/status/status_test.go, test/e2e/setup/setup.go, test/e2e/util/mongotester/mongotester.go, test/e2e/util/wait/wait.go
Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>
fixing  https://github.com/mongodb/mongodb-kubernetes-operator/issues/1030
PS: I am using my lovely friend @AkihiroSuda tool https://github.com/AkihiroSuda/go-wrap-to-percent-w
=> remove github.com/pkg/errors

release.json, scripts/dev/templates/readiness/Dockerfile.builder
=> Bump go version to 1.18.4 for readiness probe

scripts/dev/templates/agent/Dockerfile.ubi
=> Remove outdated microdnf command from agent image

deploy/openshift/operator_openshift.yaml, release.json
Related helm-chart PR: https://github.com/mongodb/helm-charts/pull/163
=> Release MongoDB Kubernetes Operator v0.7.5

docs/build_operator_locally.md
=> Add step to download helm-chart submodule into the repo before deploying the operator

docs/how-to-release.md
Updated community operator release process docs.
=> Updated how-to-release.md

release.json
=> Bump Agent image version

.action_templates/steps/cancel-previous.yaml, .action_templates/steps/checkout-fork.yaml, .github/workflows/e2e-fork.yml, .github/workflows/e2e.yml
Security fixes to GitHub actions.
=> CLOUDP-131793: GHA security improvements

release.json
=> CLOUDP-133524 Upgrade Agent to the latest version

docs/RELEASE_NOTES.md
=> Add missing changes to release notes

.github/workflows/release-images.yml
=> Add missing AWS credentials to image release job

config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, release.json
=> Release MongoDB Kubernetes Operator v0.7.6

docs/architecture.md
Don't believe this warrants an issue.
=> Fix link to MongoDBCommunity resource definition (CRD)

docs/install-upgrade.md
Namely support for only x86-64/AMD64.
=> List prerequisites

README.md
=> Remove breaking change warning for operator version v0.6.0

release.json
=> CLOUDP-151389: Release latest agent

version/version.go
=> Remove unneeded version package

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, docs/RELEASE_NOTES.md, release.json
=> Release MongoDB Kubernetes Operator v0.7.7

Makefile, scripts/ci/dump_diagnostics.sh, scripts/dev/install_prerequisites.sh
Dev Env for M1
- updated telepresence installation script for m1
Diagnostics
- dump pod list for a quick glance which pods are broken
- dump `/var/log/mms` for mongodb-agent diagnostics
Utilities
- makefile comment for help target generation
=> [dev] [ux] dump additional logs and dev env configurations

.github/CODEOWNERS
- adds me (nammn)
- removes not existing owner
=> [codeowner] add nammn and remove non existing user

pkg/automationconfig/automation_config_builder.go
Signed-off-by: aimuz <mr.imuz@gmail.com>
=> chore: improve code readability

controllers/construct/mongodbstatefulset.go
=> [logs] add verbose agent logs and default log path

scripts/dev/setup_kind_cluster.sh
=> Sync the Kind setup with the downstream

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, docs/RELEASE_NOTES.md, release.json
=> Release MongoDB Kubernetes Operator v0.7.8

docs/deploy-configure.md
Addresses: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1207
=> Add instruction to configure cluster domain

pkg/util/merge/merge.go, pkg/util/merge/merge_service_spec.go, pkg/util/merge/merge_test.go
This Pull Request introduces Service Spec merging functionality. It is required for the downstream work.
=> CLOUDP-156372 Merge Service Spec

.github/dependabot.yml
=> Update dependabot.yml reviewers

docs/how-to-release.md
=> Pin helm-chart to 0.7.9 release

.action_templates/jobs/tests.yaml, .github/workflows/e2e-fork.yml, .github/workflows/e2e.yml, controllers/construct/build_statefulset_test.go, controllers/construct/mongodbstatefulset.go, controllers/replica_set_controller.go, controllers/replicaset_controller_test.go, pkg/automationconfig/automation_config_builder.go, pkg/automationconfig/automation_config_test.go, test/e2e/replica_set_enterprise/replica_set_enterprise_test.go, test/e2e/replica_set_enterprise_upgrade_4_5/replica_set_enterprise_upgrade_4_5.go, test/e2e/replica_set_enterprise_upgrade_5_6/replica_set_enterprise_upgrade_5_6.go
This Pull Request makes possible to run EA Server images with the Operator.
=> CLOUDP-169740 Enable use of the EA images

docs/install-upgrade.md
This Pull Request clarifies the MongoDB registry and image urls in the docs.
=> CLOUDP-169740 Small doc correction

README.md
Add in customer outreach to the readme
=> DM Update README.md

controllers/replicaset_controller_test.go, controllers/validation/validation.go
=> Add validation to ensure consistent replicas

pkg/util/merge/merge.go, pkg/util/merge/merge_test.go
=> Fix lost toleration when key duplicated

.github/workflows/release-single-image.yml, release.json
=> Bump and release agent version to  12.0.24.7719

controllers/mongodb_tls_test.go
=> chore: pkg imported more than once

.github/workflows/go.yml
https://github.com/marketplace/actions/setup-go-environment adds caching by default for more details here: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
=> update setup-go to enable caching

release.json
* Bumped agent to `12.0.25.7724-1`
* mongodb-tools to `100.7.4`
=> Bump and release agent version to 12.0.25.7724-1

release.json
Bump readiness probe version in order to release new version.
=> Bump readiness probe version to 1.0.17

Makefile, README.md, docs/README.md, docs/build_operator_locally.md, docs/deploy-configure.md, docs/prometheus/README.md, docs/secure.md
=> Fix documentation

docs/resize-pvc.md
[JIRA](https://jira.mongodb.org/browse/DOCSP-32662)
=> (DOCSP-32662) Adds docs for resizing PVC resources.

api/v1/mongodbcommunity_types.go, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, controllers/construct/build_statefulset_test.go, controllers/construct/mongodbstatefulset.go, pkg/automationconfig/automation_config.go
=> Make agent log file configurable

.github/CODEOWNERS
=> Update CODEOWNERS - removing priyo

pkg/authentication/scramcredentials/scram_credentials.go
=> chore: use copy(to, from) instead of a loop

README.md
=> Add warning for deployment with server version >= 7.0 

controllers/replica_set_controller.go, controllers/replicaset_controller_test.go, docs/RELEASE_NOTES.md
This Pull Request implements an error when user creates a CR with MDB 7
=> CLOUDP-202214 Error on MDB 7

.github/workflows/release-images.yml
=> Fix release workflow by adding QEMU to the runner

.github/workflows/release-single-image.yml
https://github.com/mongodb/mongodb-kubernetes-operator/actions/runs/6788064931/job/18452239355
=> add qemu for single images

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, docs/RELEASE_NOTES.md
=> Release MongoDB Kubernetes Operator v0.9.0

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml
=> Fixing missing operator image bump in the rest of the config

cmd/readiness/readiness_test.go, cmd/readiness/testdata/health-status-ok-with-WaitForCorrectBinaries.json
This Pull Request introduces additional tests for `WaitForCorrectBinaries` introduced in the Agent for the Operator Mode.
=> CLOUDP-204109 Additional tests for WaitForCorrectBinaries

release.json
=> Bump agent corresponding to OM 7.0.1

api/v1/mongodbcommunity_types.go, api/v1/mongodbcommunity_types_test.go, config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml, config/samples/mongodb.com_v1_mongodbcommunity_connection_string_secret_namespace.yaml, controllers/mongodb_users.go, controllers/replicaset_controller_test.go, docs/install-upgrade.md, pkg/authentication/authtypes/authtypes.go
(cherry picked from commit f904443b352455d8d44a0eb3a5e3db6933b8d1df)
=> feat: set namespace connectionStringSecret per user

go.mod, go.sum
=> CLOUDP-222583 - bump protobuf

requirements.txt
=> CLOUDP-229252 - update dnspython

pkg/kube/client/client_test.go, pkg/kube/service/service.go
Removed code that was unused in this repository.
=> Removed unused code

go.mod, go.sum
=> CLOUDP-235055 & CLOUDP-236352 bumping protobuf

requirements.txt
=> CLOUDP-247603 - bump tqdm

requirements.txt
=> CLOUDP-250100 CVE-2024-35195  fix

.action_templates/steps/dump-and-upload-diagnostics-always.yaml, .action_templates/steps/dump-and-upload-diagnostics.yaml, .github/CODEOWNERS, .github/workflows/e2e-dispatch.yml, .github/workflows/e2e-fork.yml, .github/workflows/e2e.yml
=> Update CI and codeowners

config/manager/manager.yaml, deploy/openshift/operator_openshift.yaml, docs/RELEASE_NOTES.md, docs/how-to-release.md, release.json
=> Release MongoDB Kubernetes Operator v0.12.0

README.md
=> CLOUDP-315307 - mck - MCO deprecation notice
